#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ui_framework/components.h"
#include "ui_framework/light_web.h"
#ifdef UI_SCROLL_WEBVIEW2
#include "ui_framework/webview2.h"
#endif
#include "../src/ui_internal.h"
static int failures,runtime_mode,delayed;static uint64_t total=100000;static ui_component_query_t late;
#define CHECK(x) do{if(!(x)){fprintf(stderr,"scroll line%d: %s\n",__LINE__,#x);++failures;}}while(0)
static void pump(DWORD ms){ULONGLONG start=GetTickCount64();do{MSG m;while(PeekMessageW(&m,NULL,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(1);}while(GetTickCount64()-start<ms);}
static ui_status_t present(ui_component_t *c,const char *id,ui_element_presentation_t *p){ULONGLONG start=GetTickCount64();ui_status_t s;do{s=ui_component_get_presentation(c,id,p);if(s!=UI_STATUS_PENDING){if(s!=UI_STATUS_OK||!p->visible)printf("presentation %s status=%d visible=%d rect=%d,%d,%d,%d clip=%d,%d,%d,%d\n",id,s,p->visible,p->rect.x,p->rect.y,p->rect.width,p->rect.height,p->clip.x,p->clip.y,p->clip.width,p->clip.height);return s;}pump(1);}while(GetTickCount64()-start<10000);return s;}
static void input(ui_component_t *c,ui_input_kind_t kind,int x,int y,unsigned key){ui_input_event_t e={0};e.size=sizeof(e);e.kind=kind;e.x=x;e.y=y;e.key_code=key;e.pointer_button=1;CHECK(ui_component_dispatch_input(c,&e)==UI_STATUS_OK);if(runtime_mode)pump(80);}
static void command(ui_host_t *h,uint64_t request,const char *id,const char *params,const char *origin,void *user){(void)id;(void)params;(void)origin;(void)user;ui_host_reply(h,request,1,"{}");}
static void source(ui_component_t *c,const ui_component_query_t *q,void *user){ui_row_t rows[128]={0};ui_cell_t (*cells)[64];ui_component_batch_t b={0};size_t n=q->count;if(q->kind!=UI_QUERY_ROWS)return;late=*q;late.sort_column=NULL;if(delayed)return;cells=calloc(128,sizeof(*cells));CHECK(cells!=NULL);if(!cells)return;if(n>128)n=128;if(q->first>=total)n=0;else if(n>total-q->first)n=(size_t)(total-q->first);
    for(size_t i=0;i<n;++i){rows[i].size=sizeof(rows[i]);rows[i].id=q->parent_id?1000000+q->first+i+1:q->first+i+1;rows[i].parent_id=q->parent_id;rows[i].has_children=q->parent_id?0:1;rows[i].title="stable row";rows[i].cells=cells[i];rows[i].cell_count=user?64:0;for(size_t j=0;user&&j<64;++j){cells[i][j].size=sizeof(ui_cell_t);cells[i][j].column_id=((ui_column_desc_t *)user)[j].id;cells[i][j].kind=UI_VALUE_TEXT;cells[i][j].text="value";}}
    b.size=sizeof(b);b.component_generation=q->component_generation;b.request_id=q->request_id;b.first=q->first;b.parent_id=q->parent_id;b.total_count=total;b.rows=rows;b.row_count=n;CHECK(ui_component_submit(c,&b)==UI_STATUS_OK);free(cells);}
static void scroll_only(ui_component_t *c,int table,int height)
{ui_element_presentation_t p={0};p.size=sizeof(p);CHECK(present(c,"controls",&p)==UI_STATUS_OK&&!p.visible);CHECK(present(c,"next-page",&p)==UI_STATUS_NOT_FOUND);CHECK(present(c,"rows",&p)==UI_STATUS_OK&&p.visible);
 CHECK(p.rect.y<=(table?76:40));CHECK(p.rect.height>=height-(table?136:80));CHECK(late.count==((size_t)p.rect.height+31)/32+2);printf("Scroll-only viewport kind=%s y=%d height=%d query=%llu+%zu\n",table?"table":"tree/list",p.rect.y,p.rect.height,(unsigned long long)late.first,late.count);}
static void drag_end(ui_component_t *c,const char *thumb_id,const char *track_id,int horizontal,int cancel){ui_element_presentation_t thumb={0},track={0};thumb.size=track.size=sizeof(thumb);CHECK(present(c,thumb_id,&thumb)==UI_STATUS_OK&&thumb.visible);CHECK(present(c,track_id,&track)==UI_STATUS_OK&&track.visible);if(!thumb.visible||!track.visible)return;
    input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+thumb.rect.width/2,thumb.rect.y+thumb.rect.height/2,0);input(c,UI_INPUT_POINTER_MOVE,horizontal?track.rect.x+track.rect.width+100:thumb.rect.x+thumb.rect.width/2,horizontal?thumb.rect.y+thumb.rect.height/2:track.rect.y+track.rect.height+100,0);
    if(cancel)input(c,UI_INPUT_KEY_DOWN,0,0,27);else input(c,UI_INPUT_POINTER_UP,horizontal?track.rect.x+track.rect.width+100:thumb.rect.x+thumb.rect.width/2,horizontal?thumb.rect.y+thumb.rect.height/2:track.rect.y+track.rect.height+100,0);}
int main(int argc,char **argv){ui_host_config_t hc={0};ui_host_t *h;ui_component_t *c;ui_component_desc_t d={0};ui_column_desc_t columns[64]={0};char ids[64][12];ui_native_shell_t *native=NULL;ui_web_backend_t *backend=NULL;HWND root=NULL;ui_component_state_t s={0};ui_element_presentation_t p={0};
    runtime_mode=argc==2&&!strcmp(argv[1],"--webview2");
#ifndef UI_SCROLL_WEBVIEW2
    if(runtime_mode){fprintf(stderr,"WebView2 was not enabled for this test\n");return 1;}
#endif
    CHECK(ui_framework_initialize()==UI_STATUS_OK);
#ifdef UI_SCROLL_WEBVIEW2
    if(runtime_mode){ui_webview2_backend_config_t config={0};ui_status_t status;root=CreateWindowW(L"STATIC",L"Complete data scrollbar Runtime",WS_OVERLAPPEDWINDOW,0,0,850,550,NULL,NULL,NULL,NULL);ShowWindow(root,SW_SHOWNOACTIVATE);hc.native_parent=root;config.size=sizeof(config);config.framework_components=1;backend=ui_webview2_backend_create(&config,&status);CHECK(backend!=NULL);if(!backend)return 1;}
#endif
    hc.size=sizeof(hc);hc.api_version=UI_FRAMEWORK_API_VERSION;h=ui_host_create(&hc);CHECK(h!=NULL);if(!h)return 1;if(runtime_mode){ui_native_shell_config_t config={0};CHECK(ui_host_resize(h,800,500)==UI_STATUS_OK);config.size=sizeof(config);config.host=h;native=ui_native_shell_create_web(&config);CHECK(native!=NULL);}
    for(size_t i=0;i<64;++i){snprintf(ids[i],sizeof(ids[i]),"c%zu",i);columns[i].size=sizeof(columns[i]);columns[i].id=ids[i];columns[i].title=ids[i];columns[i].width=180;columns[i].kind=UI_VALUE_TEXT;}
    {ui_command_desc_t cmd={0};cmd.size=sizeof(cmd);cmd.id="sort";cmd.title="Datasource sort";cmd.handler=command;CHECK(ui_host_register_command(h,&cmd)==UI_STATUS_OK);}
    d.size=sizeof(d);d.sort_command="sort";d.id="table";d.kind=UI_COMPONENT_TABLE;d.columns=columns;d.column_count=64;d.source=source;d.user_data=columns;d.web_backend=backend;CHECK(ui_component_register(h,&d,&c)==UI_STATUS_OK);CHECK((runtime_mode?ui_component_mount(c,ui_shell_get_content_slot(ui_host_get_shell(h),NULL)):ui_component_mount_offscreen(c,800,500,96))==UI_STATUS_OK);
    s.size=sizeof(s);p.size=sizeof(p);scroll_only(c,1,500);CHECK(present(c,"scroll-v-thumb",&p)==UI_STATUS_OK&&p.visible&&p.rect.height>=24);drag_end(c,"scroll-v-thumb","scroll-v-track",0,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first>99900&&s.first<100000);printf("end row first=%llu total=%llu rows=%zu query=%llu+%zu nodes=%zu status=%d\n",(unsigned long long)s.first,(unsigned long long)s.total_count,s.row_count,(unsigned long long)late.first,late.count,s.rendered_nodes,s.presentation_status);{char row[96];snprintf(row,sizeof(row),"cell-100000-c0");CHECK(present(c,row,&p)==UI_STATUS_OK&&p.visible);}
    CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);drag_end(c,"scroll-v-thumb","scroll-v-track",0,1);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0);
    drag_end(c,"scroll-h-thumb","scroll-h-track",1,0);printf("end column first=%llu col=%zu rows=%zu query=%llu+%zu\n",(unsigned long long)s.first,s.first_column,s.row_count,(unsigned long long)late.first,late.count);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first_column==63);CHECK(present(c,"cell-1-c63",&p)==UI_STATUS_OK&&p.visible);
    total=UINT64_MAX;CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK);printf("max initial total=%llu status=%d col=%zu query=%llu+%zu\n",(unsigned long long)s.total_count,s.presentation_status,s.first_column,(unsigned long long)late.first,late.count);drag_end(c,"scroll-v-thumb","scroll-v-track",0,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first>UINT64_MAX-128);printf("uint64 endpoint first=%llu total=%llu\n",(unsigned long long)s.first,(unsigned long long)s.total_count);
    total=1;CHECK(ui_component_query(c,0,s.first,16,0,6)==UI_STATUS_OK);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0&&s.total_count==1);
    for(int n=0;n<2;++n){total=(uint64_t)n;CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);CHECK(present(c,"scroll-v-track",&p)==UI_STATUS_OK&&!p.visible);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0&&s.total_count==total);}
    total=100000;CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);delayed=1;CHECK(ui_component_query(c,0,50000,16,0,6)==UI_STATUS_OK);{ui_component_query_t saved=late;ui_component_batch_t b={0};delayed=0;CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);b.size=sizeof(b);b.component_generation=saved.component_generation;b.request_id=saved.request_id;b.first=saved.first;b.total_count=total;CHECK(ui_component_submit(c,&b)==UI_STATUS_CANCELLED);}

    total=100000;CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);
    {ui_element_presentation_t thumb={0},track={0};ui_input_event_t e={0};thumb.size=track.size=sizeof(thumb);CHECK(present(c,"scroll-v-thumb",&thumb)==UI_STATUS_OK);CHECK(present(c,"scroll-v-track",&track)==UI_STATUS_OK);
     input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+5,thumb.rect.y+5,0);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);e.size=sizeof(e);e.kind=UI_INPUT_CANCEL;CHECK(ui_component_dispatch_input(c,&e)==UI_STATUS_OK);if(runtime_mode)pump(100);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0);
     input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+5,thumb.rect.y+5,0);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_set_sort(c,"c0",-1)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);input(c,UI_INPUT_POINTER_UP,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0);
     CHECK(present(c,"scroll-v-thumb",&thumb)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+5,thumb.rect.y+5,0);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK);{uint64_t position=s.first;ui_components_active(h,0);if(runtime_mode)pump(100);ui_components_active(h,1);if(runtime_mode)pump(100);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==position);}CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);
     CHECK(present(c,"scroll-v-thumb",&thumb)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+5,thumb.rect.y+5,0);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);
     CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);CHECK(ui_component_query(c,0,500,16,0,6)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);input(c,UI_INPUT_POINTER_UP,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==500);
     CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);CHECK(present(c,"scroll-v-thumb",&thumb)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_DOWN,thumb.rect.x+5,thumb.rect.y+5,0);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK);
     total=1;CHECK(ui_component_query(c,0,s.first,16,0,6)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_MOVE,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);input(c,UI_INPUT_POINTER_UP,thumb.rect.x+5,track.rect.y+track.rect.height+100,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first==0&&s.total_count==1);
     total=100000;CHECK(ui_component_set_source(c,source,columns)==UI_STATUS_OK);CHECK(ui_component_query(c,0,0,16,0,6)==UI_STATUS_OK);
     CHECK(present(c,"scroll-v-track",&track)==UI_STATUS_OK);input(c,UI_INPUT_POINTER_DOWN,track.rect.x+5,track.rect.y+track.rect.height-2,0);input(c,UI_INPUT_POINTER_UP,track.rect.x+5,track.rect.y+track.rect.height-2,0);CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.first>0&&s.first<128);}
    for(int kind=UI_COMPONENT_TREE;kind<=UI_COMPONENT_LIST;kind+=2){ui_component_t *simple;d.id=kind==UI_COMPONENT_TREE?"tree-range":"list-range";d.kind=(ui_component_kind_t)kind;d.column_count=0;d.columns=NULL;d.sort_command=NULL;d.user_data=NULL;CHECK(ui_component_register(h,&d,&simple)==UI_STATUS_OK);
     CHECK((runtime_mode?ui_component_mount(simple,ui_shell_get_content_slot(ui_host_get_shell(h),NULL)):ui_component_mount_offscreen(simple,800,500,96))==UI_STATUS_OK);
     scroll_only(simple,0,500);if(kind==UI_COMPONENT_TREE){CHECK(ui_component_expand(simple,1,1)==UI_STATUS_OK);CHECK(ui_component_get_state(simple,&s)==UI_STATUS_OK&&s.total_count==200000);drag_end(simple,"scroll-v-thumb","scroll-v-track",0,0);CHECK(ui_component_get_state(simple,&s)==UI_STATUS_OK&&s.first>199900);CHECK(ui_component_expand(simple,1,0)==UI_STATUS_OK);CHECK(ui_component_get_state(simple,&s)==UI_STATUS_OK&&s.first<100000&&s.total_count==100000);}
     drag_end(simple,"scroll-v-thumb","scroll-v-track",0,0);CHECK(ui_component_get_state(simple,&s)==UI_STATUS_OK&&s.first>99900&&s.first<100000&&s.rendered_nodes<=1024&&s.cached_bytes<=2097152);}
    CHECK(ui_component_get_state(c,&s)==UI_STATUS_OK&&s.rendered_nodes<=1024&&s.cached_bytes<=2097152);if(native)ui_native_shell_destroy(native);ui_host_destroy(h);
#ifdef UI_SCROLL_WEBVIEW2
    if(backend){ui_webview2_backend_destroy(backend);pump(2000);}
#endif
    if(root)DestroyWindow(root);printf("complete range scroll %s: %d failures\n",runtime_mode?"actual Runtime":"light offscreen",failures);return failures?1:0;}
