/* Public C only: actual pointer/keyboard and desktop frames; no application DLL. */
#define WIN32_LEAN_AND_MEAN
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ui_framework/components.h"
#include "ui_framework/shell.h"
static int failed,sequence;
static const char *directory;
static HWND root;
static ui_host_t *host;
static ui_native_shell_t *native;
static void check(int ok,const char *what){printf("%s %s\n",ok?"PASS":"FAIL",what);if(!ok)++failed;}
static void pump(DWORD ms){ULONGLONG end=GetTickCount64()+ms;MSG m;do{while(PeekMessageW(&m,NULL,0,0,PM_REMOVE)){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(5);}while(GetTickCount64()<end);}
static LRESULT CALLBACK proc(HWND w,UINT m,WPARAM a,LPARAM b){intptr_t result;if(native&&ui_native_shell_handle_message(native,w,m,a,b,&result)==UI_STATUS_OK)return result;return DefWindowProcW(w,m,a,b);}
static void mouse(int x,int y,DWORD flags,LONG data)
{INPUT i={0};i.type=INPUT_MOUSE;i.mi.dx=MulDiv(x-GetSystemMetrics(SM_XVIRTUALSCREEN),65535,GetSystemMetrics(SM_CXVIRTUALSCREEN)-1);i.mi.dy=MulDiv(y-GetSystemMetrics(SM_YVIRTUALSCREEN),65535,GetSystemMetrics(SM_CYVIRTUALSCREEN)-1);i.mi.dwFlags=MOUSEEVENTF_ABSOLUTE|MOUSEEVENTF_VIRTUALDESK|MOUSEEVENTF_MOVE|flags;i.mi.mouseData=(DWORD)data;check(SendInput(1,&i,sizeof(i))==1,"SendInput mouse");pump(60);}
static void key(WORD k,int control)
{INPUT a[4]={0};int n=0;if(control){a[n].type=INPUT_KEYBOARD;a[n++].ki.wVk=VK_CONTROL;}a[n].type=INPUT_KEYBOARD;a[n++].ki.wVk=k;a[n].type=INPUT_KEYBOARD;a[n].ki.wVk=k;a[n++].ki.dwFlags=KEYEVENTF_KEYUP;if(control){a[n].type=INPUT_KEYBOARD;a[n].ki.wVk=VK_CONTROL;a[n++].ki.dwFlags=KEYEVENTF_KEYUP;}check(SendInput(n,a,sizeof(INPUT))==(UINT)n,"SendInput keyboard");pump(80);}
static void frame(const char *name)
{int x=GetSystemMetrics(SM_XVIRTUALSCREEN),y=GetSystemMetrics(SM_YVIRTUALSCREEN),w=GetSystemMetrics(SM_CXVIRTUALSCREEN),h=GetSystemMetrics(SM_CYVIRTUALSCREEN);HDC screen=GetDC(NULL),dc=CreateCompatibleDC(screen);BITMAPINFO info={0};BITMAPFILEHEADER header={0};void *pixels;HBITMAP bitmap;HGDIOBJ old;FILE *f;char path[1024];POINT at;DWORD pid=0;HWND hit;wchar_t cls[128];
 info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=w;info.bmiHeader.biHeight=-h;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;bitmap=CreateDIBSection(screen,&info,DIB_RGB_COLORS,&pixels,NULL,0);old=SelectObject(dc,bitmap);check(BitBlt(dc,0,0,w,h,screen,x,y,SRCCOPY|CAPTUREBLT),"desktop capture");header.bfType=0x4d42;header.bfOffBits=sizeof(header)+sizeof(info.bmiHeader);header.bfSize=header.bfOffBits+w*h*4;snprintf(path,sizeof(path),"%s/%03d-%s.bmp",directory,sequence++,name);f=fopen(path,"wb");if(f){fwrite(&header,1,sizeof(header),f);fwrite(&info.bmiHeader,1,sizeof(info.bmiHeader),f);fwrite(pixels,1,w*h*4,f);fclose(f);}else check(0,"write frame");GetCursorPos(&at);hit=WindowFromPoint(at);GetClassNameW(hit,cls,128);GetWindowThreadProcessId(hit,&pid);printf("FRAME tick=%llu name=%s button=%d capture=%p hit=%p class=%ls pid=%lu xy=%ld,%ld focus=%p\n",GetTickCount64(),name,(GetAsyncKeyState(VK_LBUTTON)&0x8000)!=0,(void *)GetCapture(),(void *)hit,cls,pid,at.x,at.y,(void *)GetFocus());SelectObject(dc,old);DeleteObject(bitmap);DeleteDC(dc);ReleaseDC(NULL,screen);}

static void resize_host(int width,int dpi)
{RECT r;SetWindowPos(root,NULL,60,60,width,470,SWP_NOZORDER);check(ui_host_set_dpi(host,(uint32_t)dpi)==UI_STATUS_OK,"set program DPI");GetClientRect(root,&r);check(ui_host_resize(host,MulDiv(r.right,96,dpi),MulDiv(r.bottom,96,dpi))==UI_STATUS_OK,"logical resize");check(ui_native_shell_reflow(native)==UI_STATUS_OK,"reflow");pump(100);{uint32_t actual=0;ui_host_get_dpi(host,&actual);printf("DPI requested=%d host=%u window=%u client=%ld,%ld\n",dpi,actual,GetDpiForWindow(root),r.right,r.bottom);}}
static void rows(ui_component_t *c,const ui_component_query_t *q,void *data)
{const char *ids[]={"a","b","c","d"};ui_row_t r[2]={0};ui_cell_t v[2][4]={0};ui_component_batch_t batch={0};size_t n=q->first<2?2-(size_t)q->first:0;(void)data;if(q->kind!=UI_QUERY_ROWS)return;if(n>q->count)n=q->count;for(size_t i=0;i<n;++i){r[i].size=sizeof(r[i]);r[i].id=q->first+i+1;r[i].title="Row";r[i].cells=v[i];r[i].cell_count=q->column_count;r[i].content_version=1;for(size_t j=0;j<q->column_count;++j){v[i][j].size=sizeof(v[i][j]);v[i][j].column_id=ids[q->first_column+j];v[i][j].kind=UI_VALUE_TEXT;v[i][j].text="Cell text";}}batch.size=sizeof(batch);batch.component_generation=q->component_generation;batch.request_id=q->request_id;batch.first=q->first;batch.total_count=2;batch.rows=r;batch.row_count=n;check(ui_component_submit(c,&batch)==UI_STATUS_OK,"table rows");}
static ui_component_t *table(ui_content_slot_t *slot)
{ui_component_desc_t d={0};ui_column_desc_t cols[4]={0};const char *ids[]={"a","b","c","d"};ui_component_t *c;for(int i=0;i<4;++i){cols[i].size=sizeof(cols[i]);cols[i].id=ids[i];cols[i].title=i==3?"END COLUMN":"Long narrow header";cols[i].width=110;cols[i].kind=UI_VALUE_TEXT;}d.size=sizeof(d);d.id="table";d.title="Public header";d.kind=UI_COMPONENT_TABLE;d.columns=cols;d.column_count=4;d.source=rows;check(ui_component_register(host,&d,&c)==UI_STATUS_OK,"table register");check(ui_component_mount(c,slot)==UI_STATUS_OK,"table mount");pump(100);return c;}
static int header_capture(ui_component_t *c,int dpi,unsigned char **pixels,size_t *length)
{ui_element_presentation_t p={0};ui_pixel_buffer_t b={0};p.size=sizeof(p);check(ui_component_get_presentation(c,"columns",&p)==UI_STATUS_OK,"column rectangle");b.size=sizeof(b);{ui_rect_t rect;if(ui_content_slot_get_rect(ui_shell_get_content_slot(ui_host_get_shell(host),NULL),&rect)!=UI_STATUS_OK)return 0;if(ui_component_capture_rgba(c,rect.width,rect.height,(uint32_t)dpi,&b)!=UI_STATUS_OK)return 0;b.capacity=b.stride*b.height;b.pixels=malloc(b.capacity);if(!b.pixels)return 0;if(ui_component_capture_rgba(c,rect.width,rect.height,(uint32_t)dpi,&b)!=UI_STATUS_OK){free(b.pixels);return 0;}}{int y=MulDiv(p.rect.y,dpi,96),h=MulDiv(p.rect.height,dpi,96);if(y<0||y+h>(int)b.height){free(b.pixels);return 0;}*length=(size_t)b.width*h*4;*pixels=malloc(*length);for(int i=0;i<h;++i)memcpy(*pixels+(size_t)i*b.width*4,b.pixels+(size_t)(y+i)*b.stride,(size_t)b.width*4);}free(b.pixels);return 1;}
int main(int argc,char **argv)
{ui_host_config_t hc={0};ui_native_shell_config_t sc={0};ui_layout_desc_t layout={0};ui_content_slot_t *slot;WNDCLASSW wc={0};char text[2048],name[80];directory=argc>1?argv[1]:".";ui_framework_initialize();wc.lpfnWndProc=proc;wc.hInstance=GetModuleHandleW(NULL);wc.hbrBackground=GetSysColorBrush(COLOR_WINDOW);wc.hCursor=LoadCursorW(NULL,MAKEINTRESOURCEW(32512));wc.lpszClassName=L"UIFrameworkPublicDisplayProbe";RegisterClassW(&wc);root=CreateWindowW(wc.lpszClassName,L"PUBLIC C DISPLAY PROBE - one instance",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,60,60,900,470,NULL,NULL,wc.hInstance,NULL);hc.size=sizeof(hc);hc.api_version=UI_FRAMEWORK_API_VERSION;hc.native_parent=root;host=ui_host_create(&hc);layout.size=sizeof(layout);ui_host_set_layout(host,&layout);sc.size=sizeof(sc);sc.host=host;sc.native_parent=root;native=ui_native_shell_create_web(&sc);slot=ui_shell_get_content_slot(ui_host_get_shell(host),NULL);ShowWindow(root,SW_SHOW);SetForegroundWindow(root);
 {HMODULE module=LoadLibraryW(L"Shcore.dll");HRESULT (WINAPI *get_dpi)(HMONITOR,int,UINT *,UINT *)=module?(void *)GetProcAddress(module,"GetDpiForMonitor"):NULL;UINT x=0,y=0;if(get_dpi){HRESULT result=get_dpi(MonitorFromWindow(root,MONITOR_DEFAULTTONEAREST),0,&x,&y);printf("MONITOR reported-effective=%u,%u result=%ld monitors=%d\n",x,y,result,GetSystemMetrics(SM_CMONITORS));result=get_dpi(MonitorFromWindow(root,MONITOR_DEFAULTTONEAREST),2,&x,&y);printf("MONITOR reported-raw=%u,%u result=%ld (not physical 192 acceptance)\n",x,y,result);}if(module)FreeLibrary(module);}
 strcpy(text,"START_MARKER ");for(int i=0;i<25;++i)strcat(text,"abcdefghijklmnopqrstuvwxyz0123456789 ");strcat(text,"TAIL_MARKER_20261009");
 for(int dpi=96;dpi<=192;dpi+=96){ui_component_t *c;ui_component_desc_t d={0};ui_field_desc_t field={0};ui_cell_t value={0};ui_element_presentation_t p={0};HWND view;POINT at,caret;resize_host(900,dpi);field.size=sizeof(field);field.id="editable";field.title="Text";field.kind=UI_VALUE_TEXT;d.size=sizeof(d);d.id="edit";d.title="Public long editable";d.kind=UI_COMPONENT_FORM;d.fields=&field;d.field_count=1;check(ui_component_register(host,&d,&c)==UI_STATUS_OK,"editor register");value.size=sizeof(value);value.kind=UI_VALUE_TEXT;value.text=text;check(ui_component_set_field(c,"editable",&value)==UI_STATUS_OK,"long editable value");check(ui_component_mount(c,slot)==UI_STATUS_OK,"editor mount");view=FindWindowExW((HWND)ui_content_slot_native_handle(slot),NULL,L"UIFrameworkLightWeb",NULL);
 for(int width=900;width>=350;width-=550){resize_host(width,dpi);p.size=sizeof(p);check(ui_component_get_presentation(c,"field-editable",&p)==UI_STATUS_OK,"input rectangle");at=(POINT){MulDiv(p.rect.x+20,dpi,96),MulDiv(p.rect.y+10,dpi,96)};ClientToScreen(view,&at);mouse(at.x,at.y,MOUSEEVENTF_LEFTDOWN,0);mouse(at.x,at.y,MOUSEEVENTF_LEFTUP,0);key(VK_END,0);GetCaretPos(&caret);printf("CARET End=%ld,%ld input=%d,%d,%d,%d dpi=%d\n",caret.x,caret.y,p.rect.x,p.rect.y,p.rect.width,p.rect.height,dpi);check(GetFocus()==view&&caret.x>=MulDiv(p.clip.x,dpi,96)&&caret.x<MulDiv(p.clip.x+p.clip.width,dpi,96),"End caret actually inside visible field");check(caret.x>=MulDiv(p.rect.x+p.rect.width-20,dpi,96),"long End caret reaches right edge and exposes tail");snprintf(name,sizeof(name),"dpi-%d-width-%d-End",dpi,width);frame(name);key(VK_HOME,0);GetCaretPos(&caret);check(caret.x>=MulDiv(p.clip.x,dpi,96)&&caret.x<MulDiv(p.clip.x+p.clip.width,dpi,96),"Home caret inside visible field");snprintf(name,sizeof(name),"dpi-%d-width-%d-Home",dpi,width);frame(name);}
 ui_component_unregister(c);resize_host(900,dpi);c=table(slot);resize_host(350,dpi);mouse(75,95,0,0);snprintf(name,sizeof(name),"dpi-%d-header-resized",dpi);frame(name);{unsigned char *a=NULL,*b=NULL;size_t na=0,nb=0;check(header_capture(c,dpi,&a,&na),"resized header capture");ui_component_unregister(c);c=table(slot);snprintf(name,sizeof(name),"dpi-%d-header-fresh",dpi);frame(name);check(header_capture(c,dpi,&b,&nb),"fresh header capture");check(na==nb&&a&&b&&!memcmp(a,b,na),"resized header pixels equal fresh header pixels");free(a);free(b);}ui_component_unregister(c);}
 {ui_native_shell_t *old=native;native=NULL;ui_native_shell_destroy(old);}ui_host_destroy(host);DestroyWindow(root);printf("DISPLAY failures=%d. Program DPI and monitor DPI are distinct.\n",failed);return failed?1:0;}
