/* Complete DLL, actual HWND/SendInput and cross-process preference proof. */
#define wmain stateful_original_main
#include "stateful_components.c"
#undef wmain
static HWND language_popup,language_dialog;
static int semantic_input;
static BOOL CALLBACK locate_language_popup(HWND window,LPARAM unused)
{wchar_t name[80];(void)unused;GetClassNameW(window,name,80);if(IsWindowVisible(window)&&!wcscmp(name,L"UIFrameworkWebDialog3"))language_dialog=window;if(IsWindowVisible(window)&&!wcscmp(name,L"UIFrameworkRegisteredMenu4"))language_popup=window;return TRUE;}
static void click_rect(HWND window,const ui_rect_t *rect,uint32_t dpi)
{POINT point={MulDiv(rect->x+rect->width/2,(int)dpi,96),MulDiv(rect->y+rect->height/2,(int)dpi,96)};DWORD pid=0;wchar_t name[80];CHECK(rect->width>0&&rect->height>0);CHECK(ClientToScreen(window,&point));HWND hit=WindowFromPoint(point);GetWindowThreadProcessId(hit,&pid);GetClassNameW(hit,name,80);printf("REAL_CLICK client%d,%d %dx%d screen%ld,%ld hit%p %ls pid%lu\n",rect->x,rect->y,rect->width,rect->height,point.x,point.y,(void *)hit,name,pid);CHECK(pid==GetCurrentProcessId());CHECK(mouse(point,MOUSEEVENTF_LEFTDOWN));pump(40);CHECK(mouse(point,MOUSEEVENTF_LEFTUP));pump(150);}
static void chrome_click(host_window_t *h,const char *id)
{ui_element_presentation_t p={0};ULONGLONG end=GetTickCount64()+10000;ui_status_t status;do{p.size=sizeof(p);status=ui_web_view_get_presentation(h->view,id,&p);if(status==UI_STATUS_OK)break;pump(1);}while(GetTickCount64()<end);CHECK(status==UI_STATUS_OK&&p.visible);if(status==UI_STATUS_OK&&p.visible){if(semantic_input){ui_input_event_t e={0};e.size=sizeof(e);e.pointer_button=1;e.x=p.clip.x+p.clip.width/2;e.y=p.clip.y+p.clip.height/2;e.kind=UI_INPUT_POINTER_DOWN;CHECK(ui_web_view_dispatch_input(h->view,&e)==UI_STATUS_OK);e.kind=UI_INPUT_POINTER_UP;CHECK(ui_web_view_dispatch_input(h->view,&e)==UI_STATUS_OK);pump(100);}else click_rect(h->web_hwnd,&p.clip,h->dpi);}}
static void choose_language(host_window_t *h,ui_host_t *host,const char *id)
{
    uint64_t hash=UINT64_C(1469598103934665603);char menu[80];for(const unsigned char *p=(const unsigned char *)"Language";*p;++p){hash^=*p;hash*=UINT64_C(1099511628211);}snprintf(menu,sizeof(menu),"app-menu-%llu",(unsigned long long)hash);chrome_click(h,menu);
    ui_element_presentation_t item={0};ui_status_t status;ULONGLONG end=GetTickCount64()+10000;
    do{item.size=sizeof(item);status=ui_host_menu_get_item_presentation(host,id,&item);if(status==UI_STATUS_OK)break;pump(1);}while(GetTickCount64()<end);
    language_popup=NULL;EnumThreadWindows(GetCurrentThreadId(),locate_language_popup,0);CHECK(status==UI_STATUS_OK&&item.visible&&language_popup);if(status==UI_STATUS_OK&&language_popup){if(semantic_input){ui_input_event_t key={0};key.size=sizeof(key);key.kind=UI_INPUT_KEY_DOWN;if(strcmp(id,"language.zh")){key.key_code=40;CHECK(ui_host_menu_dispatch_input(host,&key)==UI_STATUS_OK);}key.key_code=13;CHECK(ui_host_menu_dispatch_input(host,&key)==UI_STATUS_OK);key.kind=UI_INPUT_KEY_UP;CHECK(ui_host_menu_dispatch_input(host,&key)==UI_STATUS_OK);pump(100);}else click_rect(language_popup,&item.clip,h->dpi);}
    const char *expected=!strcmp(id,"language.zh")?"zh-CN":"en-US";end=GetTickCount64()+10000;while(strcmp(h->chrome_host->language.language,expected)&&GetTickCount64()<end)pump(1);CHECK(!strcmp(h->chrome_host->language.language,expected));
}
static void language_is(ui_host_t *host,const char *code)
{ui_language_info_t info={0};info.size=sizeof(info);CHECK(ui_host_get_language(host,&info)==UI_STATUS_OK&&!strcmp(info.language,code)&&info.source==UI_LANGUAGE_APPLICATION);}
static void text_is(host_window_t *h,ui_component_t *table,ui_component_t *form,int chinese)
{
    ui_element_presentation_t p={0};CHECK(present(table,"sort-name",&p)==UI_STATUS_OK&&strstr(p.text_utf8,chinese?"名称":"Name"));
    CHECK(present(form,"label-name",&p)==UI_STATUS_OK&&strstr(p.text_utf8,chinese?"草稿":"Draft"));
    ui_language_info_t info={0};info.size=sizeof(info);CHECK(ui_host_get_language(h->chrome_host,&info)==UI_STATUS_OK&&!strcmp(info.language,chinese?"zh-CN":"en-US"));
    printf("VISIBLE_LANGUAGE %s header=%s generation%llu source%d\n",info.language,p.text_utf8,(unsigned long long)info.generation,info.source);
}
#include "language_preferences.inc"
int wmain(int argc,wchar_t **argv)
{
    host_window_t h={0};ui_app_instance_info_t a={0},b={0};wchar_t provider[4096];uint32_t dpi=argc>6?(uint32_t)_wtoi(argv[6]):96;int restoring=argc>5&&(!wcscmp(argv[5],L"restore")||!wcscmp(argv[5],L"semantic-restore"));
    if(argc<6)return 2;semantic_input=!wcsncmp(argv[5],L"semantic",8);setvbuf(stdout,NULL,_IONBF,0);printf("INPUT_EVIDENCE %s\n",!wcscmp(argv[5],L"preferences")?"complete DLL preference startup; no injected input":semantic_input?"public input diagnostic; NOT physical mouse acceptance":"real SendInput; final state checked");CHECK(SUCCEEDED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)));CHECK(ui_framework_initialize()==UI_STATUS_OK);
    CHECK(GetFullPathNameW(argv[2],4096,provider,NULL)>0);SetEnvironmentVariableW(L"UI_API7_OSMESA_DLL",provider);SetEnvironmentVariableW(L"UI_API7_BACKEND",argv[3]);SetEnvironmentVariableW(L"UI_STATE_EXAMPLE_HOME",argv[4]);
    phase("create-host-begin");HWND root=create_host(&h,GetModuleHandleW(NULL));phase("create-host-end");CHECK(root!=NULL);if(!root)return 2;h.dpi=dpi;ShowWindow(root,SW_SHOW);SetWindowPos(root,HWND_TOPMOST,40,40,min(MulDiv(1200,(int)dpi,96),GetSystemMetrics(SM_CXSCREEN)-80),min(MulDiv(800,(int)dpi,96),GetSystemMetrics(SM_CYSCREEN)-80),0);SetForegroundWindow(root);layout(&h);pump(200);
    ui_language_info_t system={0},empty={0};system.size=empty.size=sizeof(system);CHECK(ui_host_get_system_language(&system)==UI_STATUS_OK&&ui_host_get_language(h.chrome_host,&empty)==UI_STATUS_OK&&empty.source==system.source&&!strcmp(empty.language,system.language));screenshot(root,argv[4],L"empty-system");
    if(!wcscmp(argv[5],L"preferences")){phase("preferences-begin");preference_cases(&h,argv[1],argv[4]);phase("preferences-end");SendMessageW(root,WM_CLOSE,0,0);pump(300);CHECK(!IsWindow(root));phase("com-uninitialize-begin");CoUninitialize();phase("process-return");printf("Complete DLL preferences %ls failures%d\n",argv[3],failures);return failures?1:0;}
    phase("open-begin");open_path(&h,argv[1]);phase("open-return");pump(600);phase("open-settled");CHECK(get_instance(&h,ui_workspace_active(h.workspace),&a));if(!a.host)return 2;
    ui_component_t *table=ui_component_find(a.host,"table"),*form=ui_component_find(a.host,"form"),*viewport=ui_component_find(a.host,"viewport");CHECK(table&&form&&viewport);if(!table||!form||!viewport)return 2;
    language_is(a.host,restoring?"zh-CN":"en-US");text_is(&h,table,form,restoring);if(!restoring)screenshot(root,argv[4],L"english-full");
    ui_component_state_t before={0},after={0};before.size=after.size=sizeof(before);CHECK(ui_component_get_state(table,&before)==UI_STATUS_OK);int width=0;CHECK(ui_component_get_column_width(table,"name",&width)==UI_STATUS_OK&&width==(restoring?280:200));
    ui_cell_t draft={0};draft.size=sizeof(draft);draft.kind=UI_VALUE_TEXT;draft.text="user draft 用户草稿";draft.flags=UI_VALUE_MODIFIED;CHECK(ui_component_set_field(form,"name",&draft)==UI_STATUS_OK);CHECK(ui_component_select(table,9007199254741001ULL)==UI_STATUS_OK);
    HWND content=(HWND)ui_content_slot_native_handle(ui_shell_get_content_slot(ui_host_get_shell(a.host),"viewport"));CHECK(IsWindow(content));
    if(!restoring){choose_language(&h,a.host,"language.zh");language_is(a.host,"zh-CN");text_is(&h,table,form,1);screenshot(root,argv[4],L"chinese-full");}
    CHECK(ui_component_get_field(form,"name",&draft)==UI_STATUS_OK&&!strcmp(draft.text,"user draft 用户草稿"));CHECK(ui_component_get_state(table,&after)==UI_STATUS_OK&&after.generation==before.generation&&after.first==before.first&&after.cached_bytes<=2*1024*1024&&after.rendered_nodes<=1024);uint64_t selection[2];size_t count=0;CHECK(ui_component_get_selection(table,selection,2,&count)==UI_STATUS_OK&&count==1&&selection[0]==9007199254741001ULL);
    CHECK(content==(HWND)ui_content_slot_native_handle(ui_shell_get_content_slot(ui_host_get_shell(a.host),"viewport")));invoke(a.host,"test.render");ui_element_presentation_t pixels={0};CHECK(present(viewport,"preview-pixels",&pixels)==UI_STATUS_OK&&pixels.visible&&pixels.clip.width>0&&pixels.clip.height>0);
    if(!restoring){if(!semantic_input)resize_column(&a,table,dpi);else CHECK(ui_component_set_column_width(table,"name",280)==UI_STATUS_OK);invoke(a.host,"state.save");}
    phase("open-begin");open_path(&h,argv[1]);phase("open-return");pump(600);phase("open-settled");CHECK(get_instance(&h,ui_workspace_active(h.workspace),&b)&&b.instance_id!=a.instance_id);if(!b.host)return 2;language_is(b.host,"en-US");text_is(&h,ui_component_find(b.host,"table"),ui_component_find(b.host,"form"),0);
    if(!restoring)choose_language(&h,b.host,"language.en");uint64_t revision=h.language_revision;CHECK(ui_host_set_language(a.host,"en-US")==UI_STATUS_OK);pump(100);CHECK(h.language_revision==revision&&!strcmp(h.chrome_host->language.language,"en-US"));CHECK(ui_host_set_language(a.host,"zh-CN")==UI_STATUS_OK);pump(100);CHECK(h.language_revision==revision);screenshot(root,argv[4],L"english-dual");
    for(int cycle=0;cycle<8;++cycle){char tab[64];snprintf(tab,sizeof(tab),"tab-%llu",(unsigned long long)a.instance_id);chrome_click(&h,tab);language_is(a.host,"zh-CN");text_is(&h,table,form,1);snprintf(tab,sizeof(tab),"tab-%llu",(unsigned long long)b.instance_id);chrome_click(&h,tab);language_is(b.host,"en-US");CHECK(!strcmp(h.chrome_host->language.language,"en-US"));}
    CHECK(ui_workspace_activate(h.workspace,a.instance_id)==UI_STATUS_OK);pump(200);screenshot(root,argv[4],L"chinese-dual");uint64_t target=h.target;ui_rect_t before_rect={0},after_rect={0};ui_content_slot_t *slot=ui_shell_get_content_slot(ui_host_get_shell(a.host),NULL);CHECK(ui_content_slot_get_rect(slot,&before_rect)==UI_STATUS_OK);chrome_click(&h,"assistant-toggle");CHECK(h.assistant_expanded&&h.target==target);CHECK(ui_content_slot_get_rect(slot,&after_rect)==UI_STATUS_OK&&after_rect.width<before_rect.width);screenshot(root,argv[4],L"chinese-assistant");chrome_click(&h,"assistant-toggle");CHECK(!assistant_visible(&h)&&h.assistant_expanded<=0&&h.target==target);CHECK(ui_content_slot_get_rect(slot,&after_rect)==UI_STATUS_OK&&after_rect.width==before_rect.width);
    invoke(a.host,"test.modal");CHECK(ui_host_set_language(a.host,"en-US")==UI_STATUS_OK);pump(100);ui_component_t *dialog=ui_component_find(a.host,"dialog");ui_element_presentation_t submit={0};CHECK(present(dialog,"submit",&submit)==UI_STATUS_OK&&!strcmp(submit.text_utf8,"Submit"));CHECK(ui_host_invoke(a.host,"test.modal.close","{}","state-test")==0);language_dialog=NULL;EnumThreadWindows(GetCurrentThreadId(),locate_language_popup,0);CHECK(language_dialog!=NULL);if(language_dialog){if(semantic_input){ui_input_event_t e={0};e.size=sizeof(e);e.x=submit.clip.x+submit.clip.width/2;e.y=submit.clip.y+submit.clip.height/2;e.pointer_button=1;e.kind=UI_INPUT_POINTER_DOWN;CHECK(ui_component_dispatch_input(dialog,&e)==UI_STATUS_OK);e.kind=UI_INPUT_POINTER_UP;CHECK(ui_component_dispatch_input(dialog,&e)==UI_STATUS_OK);pump(100);}else click_rect(language_dialog,&submit.clip,dpi);}CHECK(ui_host_set_language(a.host,"zh-CN")==UI_STATUS_OK);pump(100);
    h.dark=1;layout(&h);pump(200);screenshot(root,argv[4],L"chinese-dark");CHECK(ui_host_set_language(a.host,"en-US")==UI_STATUS_OK);pump(200);screenshot(root,argv[4],L"english-dark");CHECK(ui_host_set_language(a.host,"zh-CN")==UI_STATUS_OK);SetWindowPos(root,NULL,0,0,MulDiv(620,(int)dpi,96),MulDiv(540,(int)dpi,96),SWP_NOMOVE|SWP_NOZORDER);pump(200);screenshot(root,argv[4],L"chinese-narrow");CHECK(!assistant_visible(&h)&&h.assistant_expanded<=0);
    phase("instances-close-begin");CHECK(ui_workspace_close(h.workspace,b.instance_id,UI_APP_CLOSE_TAB)==UI_STATUS_OK);ULONGLONG end=GetTickCount64()+10000;while(ui_workspace_count(h.workspace)>1&&GetTickCount64()<end)pump(1);pump(100);CHECK(ui_workspace_count(h.workspace)==1&&ui_workspace_active(h.workspace)==a.instance_id&&!strcmp(h.chrome_host->language.language,"zh-CN"));CHECK(ui_workspace_close(h.workspace,a.instance_id,UI_APP_CLOSE_TAB)==UI_STATUS_OK);end=GetTickCount64()+10000;while(ui_workspace_count(h.workspace)&&GetTickCount64()<end)pump(1);pump(100);CHECK(ui_workspace_count(h.workspace)==0&&h.chrome_host->language.source==system.source&&!strcmp(h.chrome_host->language.language,system.language));screenshot(root,argv[4],L"empty-after-close");CHECK(GetModuleHandleW(L"stateful_components_app.dll")==NULL&&GetCapture()==NULL);
    phase("close-begin");SendMessageW(root,WM_CLOSE,0,0);phase("close-request-return");pump(300);CHECK(!IsWindow(root));phase("com-uninitialize-begin");CoUninitialize();phase("process-return");printf("Instance language actual %ls %ls dpi%u failures%d\n",argv[3],argv[5],dpi,failures);return failures?1:0;
}
