/* Real host/popup input; --observe loads a caller package without commands. */
#define UI_HOST_TEST 1
#include "../examples/framework_host/main.c"
static int failures,calls;
static HWND popups[32];static size_t popup_count;static int all_windows;
#define CHECK(x) do{if(!(x)){fprintf(stderr,"line %d: %s\n",__LINE__,#x);++failures;}}while(0)
static void pump(void){MSG m;unsigned n=0;while(PeekMessageW(&m,NULL,0,0,PM_REMOVE)&&n++<5000)if(m.message!=WM_QUIT){TranslateMessage(&m);DispatchMessageW(&m);}}
static BOOL CALLBACK popup_window(HWND w,LPARAM data){wchar_t name[80];(void)data;GetClassNameW(w,name,80);if(!wcscmp(name,L"UIFrameworkRegisteredMenu4")&&(all_windows||IsWindowVisible(w))&&popup_count<32)popups[popup_count++]=w;return TRUE;}
static size_t menus(void){popup_count=0;EnumThreadWindows(GetCurrentThreadId(),popup_window,0);return popup_count;}
static int input(ui_web_view_t *v,const char *id,int move){ui_element_presentation_t p={0};ui_input_event_t e={0};p.size=sizeof(p);if(ui_web_view_get_presentation(v,id,&p)!=UI_STATUS_OK||!p.visible||!p.enabled)return 0;e.size=sizeof(e);e.x=p.clip.x+p.clip.width/2;e.y=p.clip.y+p.clip.height/2;e.kind=move?UI_INPUT_POINTER_MOVE:UI_INPUT_POINTER_DOWN;e.pointer_button=1;if(ui_web_view_dispatch_input(v,&e)!=UI_STATUS_OK)return 0;if(!move){e.kind=UI_INPUT_POINTER_UP;return ui_web_view_dispatch_input(v,&e)==UI_STATUS_OK;}return 1;}
static int native_click(ui_web_view_t *v,const char *id){ui_element_presentation_t p={0};HWND w=(HWND)ui_web_view_native_handle(v);p.size=sizeof(p);if(ui_web_view_get_presentation(v,id,&p)!=UI_STATUS_OK)return 0;PostMessageW(w,WM_LBUTTONDOWN,MK_LBUTTON,MAKELPARAM(p.clip.x+6,p.clip.y+8));PostMessageW(w,WM_LBUTTONUP,0,MAKELPARAM(p.clip.x+6,p.clip.y+8));pump();return 1;}
static void settle(unsigned ms){ULONGLONG end=GetTickCount64()+ms;do{pump();Sleep(1);}while(GetTickCount64()<end);}
static HWND child_view(HWND popup){return FindWindowExW(popup,NULL,NULL,NULL);}
static int menu_input(ui_host_t *h,const char *id,int move){ui_element_presentation_t p={0};ui_input_event_t e={0};p.size=sizeof(p);if(ui_host_menu_get_item_presentation(h,id,&p)!=UI_STATUS_OK||!p.visible||!p.enabled)return 0;e.size=sizeof(e);e.x=p.clip.x+8;e.y=p.clip.y+p.clip.height/2;e.kind=move?UI_INPUT_POINTER_MOVE:UI_INPUT_POINTER_DOWN;e.pointer_button=1;if(ui_host_menu_dispatch_input(h,&e)!=UI_STATUS_OK)return 0;if(!move){e.kind=UI_INPUT_POINTER_UP;return ui_host_menu_dispatch_input(h,&e)==UI_STATUS_OK;}return 1;}
static void entry_id(const char *path,char id[80]){uint64_t hash=UINT64_C(1469598103934665603);const unsigned char *p=(const unsigned char *)path;for(;*p;++p){hash^=*p;hash*=UINT64_C(1099511628211);}snprintf(id,80,"app-menu-%llu",(unsigned long long)hash);}
static void run(ui_host_t *h,uint64_t r,const char *c,const char *p,const char *s,void *u){(void)c;(void)p;(void)s;(void)u;++calls;(void)ui_host_reply(h,r,1,"{}");}
static void screenshot(HWND window,const wchar_t *path){RECT r;HDC dc;HBITMAP bitmap;HGDIOBJ old;BITMAPINFO info={0};BITMAPFILEHEADER header={0};void *bits;FILE *file=NULL;GetClientRect(window,&r);dc=CreateCompatibleDC(NULL);info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=r.right;info.bmiHeader.biHeight=-r.bottom;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;bitmap=CreateDIBSection(dc,&info,DIB_RGB_COLORS,&bits,NULL,0);CHECK(bitmap!=NULL);if(!bitmap){DeleteDC(dc);return;}old=SelectObject(dc,bitmap);CHECK(PrintWindow(window,dc,PW_CLIENTONLY));GdiFlush();header.bfType=0x4d42;header.bfOffBits=sizeof(header)+sizeof(info.bmiHeader);header.bfSize=header.bfOffBits+(DWORD)r.right*(DWORD)r.bottom*4;if(!_wfopen_s(&file,path,L"wb")){fwrite(&header,sizeof(header),1,file);fwrite(&info.bmiHeader,sizeof(info.bmiHeader),1,file);fwrite(bits,4,(size_t)r.right*r.bottom,file);fclose(file);}SelectObject(dc,old);DeleteObject(bitmap);DeleteDC(dc);}
static void capture(HWND window,const wchar_t *prefix,const wchar_t *suffix){wchar_t path[1024];swprintf(path,1024,L"%s-%s.bmp",prefix,suffix);screenshot(window,path);}
static char first_path[4096];
static void first_group(const ui_menu_model_entry_t *e,void *u){(void)u;if(!*first_path&&e->group)snprintf(first_path,sizeof(first_path),"%s",e->path);}
int wmain(int argc,wchar_t **argv){host_window_t h={0};HWND root;ui_app_instance_info_t a={0},b={0};uint64_t first,second;char file[80],edit[80];ui_element_presentation_t p={0};int observe=argc>3&&!wcscmp(argv[3],L"--observe");if(argc<2)return 2;CHECK(ui_framework_initialize()==UI_STATUS_OK);root=create_host(&h,GetModuleHandleW(NULL));CHECK(root!=NULL);if(!root)return 1;ShowWindow(root,SW_SHOW);MoveWindow(root,30,30,1400,900,TRUE);open_path(&h,argv[1]);pump();first=ui_workspace_active(h.workspace);CHECK(first&&get_instance(&h,first,&a));if(!first)return 1;
 if(observe){CHECK(ui_host_visit_menu(a.host,"",first_group,NULL)==UI_STATUS_OK);entry_id(first_path,file);for(int dark=0;dark<2;++dark){h.dark=dark;layout(&h);pump();if(argc>2)capture(root,argv[2],dark?L"dark-host":L"light-host");CHECK(input(h.view,file,0));pump();if(menus()&&argc>2)capture(popups[0],argv[2],dark?L"dark-menu":L"light-menu");CHECK(ui_host_close_menu(a.host)==UI_STATUS_OK);pump();}printf("Requester read-only observation: path=%s; no application commands invoked\n",first_path);}
 else{ui_command_desc_t c={0};ui_menu_item_desc_t m={0};ui_menu_popup_desc_t desc={0};ui_command_state_t state={0};HWND parent=NULL;RECT pr={0},cr={0};
  c.size=sizeof(c);c.id="desktop.probe";c.title="Probe";c.handler=run;c.shortcut_key='P';c.shortcut_modifiers=UI_INPUT_MODIFIER_CONTROL;CHECK(ui_host_register_command(a.host,&c)==UI_STATUS_OK);m.size=sizeof(m);m.id="desktop.leaf";m.title="Nested command";m.menu_path="File/Pointer/Deep";m.command_id=c.id;CHECK(ui_host_register_menu_item(a.host,&m)==UI_STATUS_OK);c.id="desktop.disabled-command";CHECK(ui_host_register_command(a.host,&c)==UI_STATUS_OK);m.command_id=c.id;m.id="desktop.disabled";m.title="Disabled";m.menu_path="File/Pointer";CHECK(ui_host_register_menu_item(a.host,&m)==UI_STATUS_OK);state.size=sizeof(state);state.visible=1;CHECK(ui_host_set_command_state(a.host,c.id,&state)==UI_STATUS_OK);pump();entry_id("File",file);entry_id("Edit",edit);
  p.size=sizeof(p);CHECK(ui_web_view_get_presentation(h.view,file,&p)==UI_STATUS_OK&&p.rect.height<=28);CHECK(input(h.view,file,0));pump();CHECK(menus()==1);if(popup_count)parent=popups[0];CHECK(menu_input(a.host,"File/Pointer",1));pump();CHECK(menus()==2);if(parent)GetWindowRect(parent,&pr);for(size_t i=0;i<popup_count;i++)if(popups[i]!=parent){GetWindowRect(popups[i],&cr);CHECK(cr.left>=pr.right-4||cr.right<=pr.left+4);}
  {HWND child=NULL;ui_element_presentation_t disabled={0};disabled.size=sizeof(disabled);CHECK(ui_host_menu_get_item_presentation(a.host,"desktop.disabled",&disabled)==UI_STATUS_OK&&!disabled.enabled);for(size_t i=0;i<popup_count;i++)if(popups[i]!=parent)child=popups[i];if(child){SendMessageW(child_view(child),WM_LBUTTONDOWN,MK_LBUTTON,MAKELPARAM(disabled.rect.x+4,disabled.rect.y+8));SendMessageW(child_view(child),WM_LBUTTONUP,0,MAKELPARAM(disabled.rect.x+4,disabled.rect.y+8));}CHECK(calls==0);
   /* Pending parent replacement is cancelled by crossing into its child. */
   if(parent&&child){PostMessageW(child_view(parent),WM_MOUSEMOVE,0,MAKELPARAM(60,50));pump();PostMessageW(child_view(child),WM_MOUSEMOVE,0,MAKELPARAM(disabled.rect.x+4,disabled.rect.y+8));settle(220);CHECK(menus()==2);}
  }
  CHECK(menu_input(a.host,"File/Pointer/Deep",1));pump();CHECK(menus()==3);for(size_t i=0;i<popup_count;i++){RECT at;POINT mid;GetWindowRect(popups[i],&at);mid.x=at.left+20;mid.y=at.top+12;CHECK(GetAncestor(WindowFromPoint(mid),GA_ROOT)==popups[i]);}if(argc>2)for(size_t i=0;i<popup_count;i++){wchar_t suffix[40];swprintf(suffix,40,L"cascade-%zu",i);capture(popups[i],argv[2],suffix);}CHECK(menu_input(a.host,"desktop.leaf",0));pump();CHECK(calls==1&&menus()==0);
  CHECK(input(h.view,file,0));pump();CHECK(native_click(h.view,file));CHECK(menus()==0);CHECK(native_click(h.view,file));CHECK(menus()==1);CHECK(input(h.view,edit,1));pump();p.size=sizeof(p);CHECK(ui_host_menu_get_presentation(a.host,"heading",&p)==UI_STATUS_OK&&!strcmp(p.text_utf8,"Edit"));CHECK(input(h.view,edit,0));pump();CHECK(menus()==0);
  desc.size=sizeof(desc);desc.path="File/Pointer";desc.anchor.size=sizeof(desc.anchor);{MONITORINFO mi={sizeof(mi)};POINT origin={0,0};GetMonitorInfoW(MonitorFromWindow(root,MONITOR_DEFAULTTONEAREST),&mi);ClientToScreen((HWND)a.host->native_parent,&origin);desc.anchor.rect.x=mi.rcWork.right-origin.x-40;}desc.anchor.rect.width=1;desc.anchor.rect.y=500;CHECK(ui_host_show_menu(a.host,&desc)==UI_STATUS_OK);CHECK(menus()==1);if(popup_count)parent=popups[0];if(parent)GetWindowRect(parent,&pr);CHECK(menu_input(a.host,"File/Pointer/Deep",1));pump();CHECK(menus()==2);for(size_t i=0;i<popup_count;i++)if(popups[i]!=parent){GetWindowRect(popups[i],&cr);CHECK(cr.right<=pr.left+4);}for(size_t i=0;i<popup_count;i++){MONITORINFO mi={sizeof(mi)};GetWindowRect(popups[i],&cr);GetMonitorInfoW(MonitorFromWindow(popups[i],MONITOR_DEFAULTTONEAREST),&mi);CHECK(cr.left>=mi.rcWork.left&&cr.right<=mi.rcWork.right&&cr.top>=mi.rcWork.top&&cr.bottom<=mi.rcWork.bottom);}CHECK(ui_host_close_menu(a.host)==UI_STATUS_OK);
  CHECK(input(h.view,file,0));pump();PostMessageW(root,WM_LBUTTONDOWN,MK_LBUTTON,MAKELPARAM(800,750));pump();CHECK(menus()==0);
  {ui_component_desc_t d={0};ui_component_t *dialog=NULL;d.size=sizeof(d);d.id="desktop.modal";d.kind=UI_COMPONENT_DIALOG;d.title="Modal probe";CHECK(ui_component_register(a.host,&d,&dialog)==UI_STATUS_OK);CHECK(input(h.view,file,0));pump();CHECK(ui_component_show_dialog(dialog)==UI_STATUS_OK);pump();CHECK(menus()==0);CHECK(ui_host_show_menu(a.host,&desc)==UI_STATUS_CANCELLED);CHECK(ui_component_close_dialog(dialog)==UI_STATUS_OK);CHECK(ui_component_unregister(dialog)==UI_STATUS_OK);}
  {HWND focus=(HWND)ui_web_view_native_handle(h.view);SetFocus(focus);DWORD handlesBefore=0,handlesAfter=0,gdiBefore=GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS),userBefore=GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS);CHECK(GetProcessHandleCount(GetCurrentProcess(),&handlesBefore));for(int cycle=0;cycle<40;cycle++){CHECK(input(h.view,file,0));pump();CHECK(menu_input(a.host,"File/Pointer",1));pump();CHECK(ui_host_close_menu(a.host)==UI_STATUS_OK);CHECK(GetFocus()==focus);}CHECK(menus()==0);CHECK(GetProcessHandleCount(GetCurrentProcess(),&handlesAfter));CHECK(handlesAfter<=handlesBefore+12);CHECK(GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS)<=gdiBefore+4);CHECK(GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS)<=userBefore+4);printf("40 menu reopen cycles: handles %lu -> %lu; GDI %lu -> %lu; USER %lu -> %lu\n",handlesBefore,handlesAfter,gdiBefore,GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS),userBefore,GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS));}
  open_path(&h,argv[1]);pump();second=ui_workspace_active(h.workspace);CHECK(second!=first&&get_instance(&h,second,&b));CHECK(ui_workspace_activate(h.workspace,first)==UI_STATUS_OK);pump();CHECK(input(h.view,file,0));pump();CHECK(ui_workspace_activate(h.workspace,second)==UI_STATUS_OK);pump();CHECK(menus()==0&&calls==1);
  for(int dpi=96;dpi<=192;dpi+=48){h.dpi=(uint32_t)dpi;MoveWindow(root,30,30,480,480,TRUE);layout(&h);pump();p.size=sizeof(p);CHECK(ui_web_view_get_presentation(h.view,"menu-more",&p)==UI_STATUS_OK&&p.visible);CHECK(input(h.view,"menu-more",0));pump();CHECK(menus()==1);CHECK(ui_host_close_menu(b.host)==UI_STATUS_OK);}if(argc>2){h.dpi=96;MoveWindow(root,30,30,1400,900,TRUE);layout(&h);pump();capture(root,argv[2],L"host");}
 }
 CHECK(ui_workspace_close_all(h.workspace)==UI_STATUS_OK);{ULONGLONG end=GetTickCount64()+5000;while(ui_workspace_count(h.workspace)&&GetTickCount64()<end){pump();ui_workspace_poll(h.workspace);SwitchToThread();}}CHECK(ui_workspace_count(h.workspace)==0);DestroyWindow(root);pump();all_windows=1;CHECK(menus()==0);printf("Desktop menu real host: %d failures; command calls=%d\n",failures,calls);return failures?1:0;
}
