/* P6: public FORM and bare textarea in the same Runtime. Private view lookup
 * is test-only observation; neither component state nor key defaults change. */
#define WIN32_LEAN_AND_MEAN
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <objbase.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ui_framework/components.h"
#include "ui_framework/shell.h"
#include "ui_framework/webview2.h"
#include "../src/ui_internal.h"
static HWND root;
static ui_native_shell_t *shell;
static const char *directory,*target="field-text";
static int failures,done,observer,frame_number;
static unsigned dispatched;
static ui_status_t script_status;
static char reply[65536];
static void check(int ok,const char *what){if(!ok){printf("FAIL %s\n",what);++failures;}}
static void pump(DWORD ms){ULONGLONG end=GetTickCount64()+ms;MSG m;do{unsigned n=0;while(n++<3000&&PeekMessageW(&m,NULL,0,0,PM_REMOVE)){if(m.message!=WM_QUIT){TranslateMessage(&m);DispatchMessageW(&m);++dispatched;}}if(GetTickCount64()<end)MsgWaitForMultipleObjects(0,NULL,FALSE,1,QS_ALLINPUT);}while(GetTickCount64()<end);}
static LRESULT CALLBACK window_proc(HWND w,UINT m,WPARAM a,LPARAM b){intptr_t r;if(shell&&ui_native_shell_handle_message(shell,w,m,a,b,&r)==UI_STATUS_OK)return r;return DefWindowProcW(w,m,a,b);}
static void result(ui_status_t status,const char *json,void *data){(void)data;script_status=status;snprintf(reply,sizeof(reply),"%s",json?json:"null");done=1;}
static int script(ui_web_view_t *v,const char *js){ULONGLONG start=GetTickCount64();do{done=0;check(ui_webview2_view_execute_script(v,js,result,NULL)==UI_STATUS_OK,"execute observation script");while(!done&&GetTickCount64()-start<5000)pump(1);if(done&&script_status==UI_STATUS_CANCELLED)printf("OBSERVATION_CANCELLED tick=%llu (presentation epoch changed; retry within original 5s gate)\n",GetTickCount64());else break;}while(GetTickCount64()-start<5000);check(done&&script_status==UI_STATUS_OK,"observation callback completes");return done&&script_status==UI_STATUS_OK;}
static int ready(ui_web_view_t *v){ULONGLONG start=GetTickCount64();int r=0,n=0;do{ui_webview2_view_get_state(v,&r,&n);if(r&&n)return 1;pump(1);}while(GetTickCount64()-start<15000);check(0,"Runtime ready/navigation");return 0;}
static void snapshot(ui_web_view_t *v,const char *phase){char js[7000];DWORD pid=0;GUITHREADINFO g={sizeof(g)};DWORD thread=GetWindowThreadProcessId(GetForegroundWindow(),&pid);GetGUIThreadInfo(thread,&g);
 snprintf(js,sizeof(js),"(function(){var e=document.getElementById('%s'),r=e.getBoundingClientRect(),s=getComputedStyle(e);return {phase:'%s',active:document.activeElement.id,hasFocus:document.hasFocus(),target:e.id,tag:e.tagName,readonly:e.readOnly,wrap:e.wrap,start:e.selectionStart,end:e.selectionEnd,direction:e.selectionDirection,length:e.value.length,line:e.value.slice(0,e.selectionStart).split('\\n').length,scrollTop:e.scrollTop,scrollLeft:e.scrollLeft,scrollHeight:e.scrollHeight,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth,clientHeight:e.clientHeight,rect:[r.x,r.y,r.width,r.height],font:s.font,lineHeight:s.lineHeight,events:window.__p6events||[]};})()",target,phase);
 if(script(v,js))printf("DOM %s\n",reply);printf("WIN phase=%s tick=%llu foreground=%p pid=%lu focus=%p active=%p ctrl=%d shift=%d alt=%d queueCtrl=%d dispatch=%u\n",phase,GetTickCount64(),(void*)GetForegroundWindow(),pid,(void*)g.hwndFocus,(void*)g.hwndActive,!!(GetAsyncKeyState(VK_CONTROL)&0x8000),!!(GetAsyncKeyState(VK_SHIFT)&0x8000),!!(GetAsyncKeyState(VK_MENU)&0x8000),!!(GetKeyState(VK_CONTROL)&0x8000),dispatched);
 if(observer)script(v,"window.__p6events=[];true");}
static LRESULT CALLBACK keyboard(int code,WPARAM kind,LPARAM data){if(code>=0){KBDLLHOOKSTRUCT *k=(KBDLLHOOKSTRUCT*)data;printf("KEY_MESSAGE tick=%llu message=%llu vk=%lu scan=%lu flags=%lu extended=%d injected=%d ctrlBefore=%d shiftBefore=%d altBefore=%d\n",GetTickCount64(),(unsigned long long)kind,k->vkCode,k->scanCode,k->flags,!!(k->flags&LLKHF_EXTENDED),!!(k->flags&LLKHF_INJECTED),!!(GetAsyncKeyState(VK_CONTROL)&0x8000),!!(GetAsyncKeyState(VK_SHIFT)&0x8000),!!(GetAsyncKeyState(VK_MENU)&0x8000));}return CallNextHookEx(NULL,code,kind,data);}
static void frame(const char *name){int w=GetSystemMetrics(SM_CXVIRTUALSCREEN),h=GetSystemMetrics(SM_CYVIRTUALSCREEN);HDC dc=GetDC(NULL),memory=CreateCompatibleDC(dc);BITMAPINFO info={0};BITMAPFILEHEADER header={0};void *pixels;char path[1024];FILE *f;RECT r;POINT p;DWORD pid=0;HBITMAP bitmap;HGDIOBJ old;
 info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=w;info.bmiHeader.biHeight=-h;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;bitmap=CreateDIBSection(dc,&info,DIB_RGB_COLORS,&pixels,NULL,0);old=SelectObject(memory,bitmap);check(BitBlt(memory,0,0,w,h,dc,GetSystemMetrics(SM_XVIRTUALSCREEN),GetSystemMetrics(SM_YVIRTUALSCREEN),SRCCOPY|CAPTUREBLT),"real desktop capture");header.bfType=0x4d42;header.bfOffBits=sizeof(header)+sizeof(info.bmiHeader);header.bfSize=header.bfOffBits+w*h*4;snprintf(path,sizeof(path),"%s/%03d-%s.bmp",directory,frame_number++,name);f=fopen(path,"wb");check(f!=NULL,"save original frame");if(f){fwrite(&header,sizeof(header),1,f);fwrite(&info.bmiHeader,sizeof(info.bmiHeader),1,f);fwrite(pixels,4,(size_t)w*h,f);fclose(f);}GetWindowRect(root,&r);GetCursorPos(&p);GetWindowThreadProcessId(WindowFromPoint(p),&pid);printf("FRAME name=%s root=%p rect=%ld,%ld,%ld,%ld cursor=%ld,%ld hitPID=%lu foreground=%p dpi=%u\n",name,(void*)root,r.left,r.top,r.right,r.bottom,p.x,p.y,pid,(void*)GetForegroundWindow(),GetDpiForWindow(root));SelectObject(memory,old);DeleteObject(bitmap);DeleteDC(memory);ReleaseDC(NULL,dc);}
static int input_allowed(void){DWORD pid=0;HDESK desktop=OpenInputDesktop(0,FALSE,DESKTOP_READOBJECTS);GetWindowThreadProcessId(GetForegroundWindow(),&pid);if(desktop)CloseDesktop(desktop);if(pid!=GetCurrentProcessId()||!desktop){check(0,"unlocked foreground belongs to probe; stop input");return 0;}return 1;}
static void click(ui_web_view_t *v){ui_element_presentation_t p={0};ui_status_t s;ULONGLONG start=GetTickCount64();POINT at;INPUT input={0};HWND hit;DWORD pid=0;p.size=sizeof(p);do{s=ui_web_view_get_presentation(v,target,&p);if(s==UI_STATUS_PENDING)pump(1);}while(s==UI_STATUS_PENDING&&GetTickCount64()-start<5000);check(s==UI_STATUS_OK&&p.clip.height>0,"public target presentation before actual click");if(s!=UI_STATUS_OK||!input_allowed())return;at=(POINT){p.clip.x+20,p.clip.y+12};ClientToScreen((HWND)ui_web_view_native_handle(v),&at);hit=WindowFromPoint(at);GetWindowThreadProcessId(hit,&pid);printf("HIT point=%ld,%ld hwnd=%p pid=%lu root=%p expected=%p\n",at.x,at.y,(void*)hit,pid,(void*)GetAncestor(hit,GA_ROOT),(void*)root);check(GetAncestor(hit,GA_ROOT)==root,"actual Runtime hit belongs to probe root");if(GetAncestor(hit,GA_ROOT)!=root)return;input.type=INPUT_MOUSE;input.mi.dx=MulDiv(at.x-GetSystemMetrics(SM_XVIRTUALSCREEN),65535,GetSystemMetrics(SM_CXVIRTUALSCREEN)-1);input.mi.dy=MulDiv(at.y-GetSystemMetrics(SM_YVIRTUALSCREEN),65535,GetSystemMetrics(SM_CYVIRTUALSCREEN)-1);input.mi.dwFlags=MOUSEEVENTF_MOVE|MOUSEEVENTF_ABSOLUTE|MOUSEEVENTF_VIRTUALDESK|MOUSEEVENTF_LEFTDOWN;check(SendInput(1,&input,sizeof(input))==1,"actual textarea mouse down");pump(1);input.mi.dwFlags&=~MOUSEEVENTF_LEFTDOWN;input.mi.dwFlags|=MOUSEEVENTF_LEFTUP;check(SendInput(1,&input,sizeof(input))==1,"actual textarea mouse up");pump(80);}
static void key(ui_web_view_t *v,WORD vk,int control,const char *phase,int picture){INPUT a[4]={0};int n=0;if(!input_allowed())return;
 if(control){a[n].type=INPUT_KEYBOARD;a[n].ki.wScan=(WORD)MapVirtualKeyW(VK_CONTROL,MAPVK_VK_TO_VSC);a[n++].ki.dwFlags=KEYEVENTF_SCANCODE;}
 for(int up=0;up<2;++up){a[n].type=INPUT_KEYBOARD;a[n].ki.wScan=(WORD)MapVirtualKeyW(vk,MAPVK_VK_TO_VSC);a[n++].ki.dwFlags=KEYEVENTF_SCANCODE|((vk>=VK_PRIOR&&vk<=VK_DOWN)?KEYEVENTF_EXTENDEDKEY:0)|(up?KEYEVENTF_KEYUP:0);}
 if(control){a[n]=a[0];a[n++].ki.dwFlags|=KEYEVENTF_KEYUP;}
 if(control){check(SendInput(1,a,sizeof(INPUT))==1,"modifier down");pump(1);check(SendInput(2,a+1,sizeof(INPUT))==2,"navigation key");pump(1);check(SendInput(1,a+3,sizeof(INPUT))==1,"modifier up");}else check(SendInput(n,a,sizeof(INPUT))==(UINT)n,"navigation key");pump(80);snapshot(v,phase);if(picture)frame(phase);{char js[1000];ULONGLONG start=GetTickCount64();snprintf(js,sizeof(js),"(function(){var e=document.getElementById('%s'),x=-1,y=-1,n=0;window.__p6settled=false;function f(){n=e.scrollTop===y&&e.scrollLeft===x?n+1:0;x=e.scrollLeft;y=e.scrollTop;if(n>=4)window.__p6settled=true;else requestAnimationFrame(f)}requestAnimationFrame(f);return true;})()",target);script(v,js);do{pump(1);script(v,"window.__p6settled");}while(strcmp(reply,"true")&&GetTickCount64()-start<5000);check(!strcmp(reply,"true"),"scroll position stabilizes in original 5s observation gate");snprintf(js,sizeof(js),"%s-settled",phase);snapshot(v,js);if(picture)frame(js);}check(!(GetAsyncKeyState(VK_CONTROL)&0x8000),"modifier released");}
static void observe(ui_web_view_t *v){if(!observer)return;script(v,"window.__p6events=[];['keydown','keyup'].forEach(function(type){document.addEventListener(type,function(ev){var e=ev.target;function record(when){window.__p6events.push({type:type,when:when,key:ev.key,code:ev.code,ctrl:ev.ctrlKey,shift:ev.shiftKey,alt:ev.altKey,target:e.id,active:document.activeElement.id,start:e.selectionStart,end:e.selectionEnd,top:e.scrollTop,left:e.scrollLeft,prevented:ev.defaultPrevented});}record('capture');requestAnimationFrame(function(){record('after-default')});},true)});true");}
static void original(ui_web_view_t *v,const char *prefix){char phase[100];snprintf(phase,sizeof(phase),"%s-original-CtrlHome",prefix);key(v,VK_HOME,1,phase,1);for(int i=0;i<19;++i){snprintf(phase,sizeof(phase),"%s-original-Down-%02d",prefix,i+1);key(v,VK_DOWN,0,phase,i==0||i==18);}snprintf(phase,sizeof(phase),"%s-original-Home",prefix);key(v,VK_HOME,0,phase,1);snprintf(phase,sizeof(phase),"%s-original-End",prefix);key(v,VK_END,0,phase,1);}
static void variants(ui_web_view_t *v,ui_component_t *component,const char *prefix,const char *text){for(int ro=1;ro>=0;--ro){ui_cell_t value={0};char js[1024];if(component){value.size=sizeof(value);value.kind=UI_VALUE_TEXT;value.flags=UI_VALUE_MULTILINE|(ro?UI_VALUE_READONLY:0);value.text=text;check(ui_component_set_field(component,"text",&value)==UI_STATUS_OK,"public read/edit state");pump(100);}else{snprintf(js,sizeof(js),"document.getElementById('native').readOnly=%s;true",ro?"true":"false");script(v,js);}for(int selected=0;selected<2;++selected)for(int ctrl=0;ctrl<2;++ctrl)for(int end=0;end<2;++end){char phase[100];snprintf(js,sizeof(js),"(function(){var e=document.getElementById('%s'),p=e.value.indexOf('LINE20 LONG')+30;e.focus();e.setSelectionRange(p,p+%d,'forward');e.scrollTop=0;return {setup:true,start:e.selectionStart,end:e.selectionEnd,active:document.activeElement.id};})()",target,selected?15:0);script(v,js);printf("SETUP %s\n",reply);snprintf(phase,sizeof(phase),"%s-ro%d-sel%d-ctrl%d-%s",prefix,ro,selected,ctrl,end?"End":"Home");snapshot(v,"before-explicit-line20-selection");key(v,end?VK_END:VK_HOME,ctrl,phase,1);}}}
int main(int argc,char **argv){ui_host_config_t hc={0};ui_native_shell_config_t sc={0};ui_webview2_backend_config_t cfg={0};ui_component_desc_t desc={0};ui_field_desc_t field={0};ui_cell_t value={0};ui_layout_desc_t layout={0};ui_component_t *component;ui_web_backend_t *backend;ui_host_t *host;ui_web_view_t *v;ui_status_t status;WNDCLASSW wc={0};char text[8192],mirror[65536],html[70000];size_t used=0;HHOOK hook=NULL;DWORD count=0;ULONGLONG start;int before_cleanup;
 directory=argc>1?argv[1]:".";observer=argc>2&&!strcmp(argv[2],"diagnostic");setvbuf(stdout,NULL,_IONBF,0);check(SUCCEEDED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)),"COM");check(ui_framework_initialize()==UI_STATUS_OK,"initialize");cfg.size=sizeof(cfg);cfg.framework_components=1;backend=ui_webview2_backend_create(&cfg,&status);check(backend&&status==UI_STATUS_OK,"real Runtime");if(!backend)return 2;
 wc.lpfnWndProc=window_proc;wc.hInstance=GetModuleHandleW(NULL);wc.hbrBackground=GetSysColorBrush(COLOR_WINDOW);wc.lpszClassName=L"UIReadonlyNavigationProbe";RegisterClassW(&wc);root=CreateWindowW(wc.lpszClassName,L"PUBLIC FORM / NATIVE TEXTAREA P6",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,80,60,650,420,NULL,NULL,wc.hInstance,NULL);hc.size=sizeof(hc);hc.api_version=UI_FRAMEWORK_API_VERSION;hc.native_parent=root;host=ui_host_create(&hc);layout.size=sizeof(layout);check(ui_host_set_layout(host,&layout)==UI_STATUS_OK,"layout");check(ui_host_resize(host,634,381)==UI_STATUS_OK,"size");sc.size=sizeof(sc);sc.host=host;sc.native_parent=root;shell=ui_native_shell_create_web(&sc);field.size=sizeof(field);field.id="text";field.title="P6 readonly content";field.kind=UI_VALUE_TEXT;desc.size=sizeof(desc);desc.id="p6";desc.title="P6 public FORM";desc.kind=UI_COMPONENT_FORM;desc.fields=&field;desc.field_count=1;desc.web_backend=backend;check(ui_component_register(host,&desc,&component)==UI_STATUS_OK,"register public FORM");for(int i=1;i<=41;++i){if(i==20){used+=snprintf(text+used,sizeof(text)-used,"LINE20 LONG ");for(int j=0;j<20;++j)used+=snprintf(text+used,sizeof(text)-used,"abcdefghijklmnopqrstuvwxyz0123456789 ");used+=snprintf(text+used,sizeof(text)-used,"LONG_TAIL20\n");}else used+=snprintf(text+used,sizeof(text)-used,"LINE%02d %s\n",i,i==41?"FINAL_LINE41_MARKER":"normal content");}value.size=sizeof(value);value.kind=UI_VALUE_TEXT;value.flags=UI_VALUE_READONLY|UI_VALUE_MULTILINE;value.text=text;check(ui_component_set_field(component,"text",&value)==UI_STATUS_OK,"41 lines");check(ui_component_mount(component,ui_shell_get_content_slot(ui_host_get_shell(host),NULL))==UI_STATUS_OK,"public mount");ShowWindow(root,SW_SHOW);{DWORD other=GetWindowThreadProcessId(GetForegroundWindow(),NULL),ours=GetCurrentThreadId();int join=other!=ours&&AttachThreadInput(other,ours,TRUE);BringWindowToTop(root);SetForegroundWindow(root);if(join)AttachThreadInput(other,ours,FALSE);}pump(100);v=host->web_views;while(v&&v->backend!=backend)v=v->host_next;check(v!=NULL,"test-only locate public FORM view");if(!v||!ready(v))return 2;printf("MODE observer=%d pid=%lu Runtime view=%p container=%p\n",observer,GetCurrentProcessId(),(void*)v,ui_web_view_native_handle(v));
 script(v,"(function(){var e=document.getElementById('field-text'),s=getComputedStyle(e),r=e.getBoundingClientRect(),css={};for(var i=0;i<s.length;++i)css[s[i]]=s.getPropertyValue(s[i]);return {value:e.value,readonly:e.readOnly,wrap:e.wrap,css:css,rect:[r.x,r.y,r.width,r.height]};})()");snprintf(mirror,sizeof(mirror),"%s",reply);printf("MIRROR %s\n",mirror);script(v,"document.getElementById('field-text').focus();true");if(observer)hook=SetWindowsHookExW(WH_KEYBOARD_LL,keyboard,GetModuleHandleW(NULL),0);click(v);observe(v);snapshot(v,"form-start");original(v,"form");if(observer)variants(v,component,"form",text);check(ui_component_unregister(component)==UI_STATUS_OK,"FORM destroy");target="native";v=ui_web_view_create(host,backend);check(v!=NULL,"public native view");check(ui_web_view_resize(v,634,381,96)==UI_STATUS_OK,"native view bounds");snprintf(html,sizeof(html),"<!doctype html><style>#native::-webkit-scrollbar{width:12px;height:12px}</style><body style='margin:0;background:white'><textarea id='native'></textarea><script>var source=%s,e=document.getElementById('native');for(var k in source.css)e.style.setProperty(k,source.css[k]);e.style.position='absolute';e.style.left=source.rect[0]+'px';e.style.top=source.rect[1]+'px';e.style.width=source.rect[2]+'px';e.style.height=source.rect[3]+'px';e.value=source.value;e.readOnly=source.readonly;e.wrap=source.wrap;</script>",mirror);check(ui_web_view_load_html(v,html)==UI_STATUS_OK,"bare native textarea load");if(!ready(v))return 2;script(v,"document.getElementById('native').focus();true");click(v);observe(v);snapshot(v,"native-start");original(v,"native");if(observer)variants(v,NULL,"native",text);ui_web_view_destroy(v);{ui_native_shell_t *old=shell;shell=NULL;ui_native_shell_destroy(old);}ui_host_destroy(host);ui_webview2_backend_destroy(backend);before_cleanup=0;start=GetTickCount64();do{HWND w=NULL;before_cleanup=0;while((w=FindWindowExW(HWND_MESSAGE,w,L"UIFrameworkWebView2Cleanup5",NULL))!=NULL)if(GetWindowThreadProcessId(w,NULL)==GetCurrentThreadId())++before_cleanup;if(!before_cleanup)break;pump(1);}while(GetTickCount64()-start<15000);check(!before_cleanup,"Runtime deferred cleanup completes");if(hook)UnhookWindowsHookEx(hook);DestroyWindow(root);GetProcessHandleCount(GetCurrentProcess(),&count);printf("FINAL pending=%d handles=%lu GDI=%lu USER=%lu dispatch=%u cleanupMs=%llu failures=%d\n",before_cleanup,count,GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS),GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS),dispatched,GetTickCount64()-start,failures);CoUninitialize();puts("PHASE process-return");return failures?1:0;}
