/* P5 public lifecycle boundaries; PENDING is permitted, never a failure itself. */
#define WIN32_LEAN_AND_MEAN
#define _WIN32_WINNT 0x0A00
#include <windows.h>
#include <objbase.h>
#include <stdio.h>
#include <stdlib.h>
#include "ui_framework/webview2.h"
#include "runtime_diagnostics.h"
static int failures,callbacks,invalid_callbacks,closed;
static unsigned dispatch;
static void check(int ok,const char *what){if(!ok){printf("FAIL %s\n",what);++failures;}}
static int pending(void){HWND w=NULL;int n=0;while((w=FindWindowExW(HWND_MESSAGE,w,L"UIFrameworkWebView2Cleanup5",NULL))!=NULL)if(GetWindowThreadProcessId(w,NULL)==GetCurrentThreadId())++n;return n;}
static void state(const char *phase,ui_web_view_t *v){DWORD handles=0;int r=0,n=0;int32_t error=0;if(v){ui_webview2_view_get_state(v,&r,&n);ui_webview2_view_get_error(v,&error);}GetProcessHandleCount(GetCurrentProcess(),&handles);printf("BOUNDARY phase=%s tick=%llu view=%p native=%p ready=%d nav=%d error=%08x pending=%d handles=%lu GDI=%lu USER=%lu callbacks=%d late=%d dispatch=%u\n",phase,GetTickCount64(),(void*)v,v?ui_web_view_native_handle(v):NULL,r,n,(unsigned)error,pending(),handles,GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS),GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS),callbacks,invalid_callbacks,dispatch);}
static void pump(void){MSG m;unsigned count=0;while(count++<3000&&PeekMessageW(&m,NULL,0,0,PM_REMOVE)){if(m.message!=WM_QUIT){TranslateMessage(&m);DispatchMessageW(&m);++dispatch;}}MsgWaitForMultipleObjects(0,NULL,FALSE,1,QS_ALLINPUT);}
static void ready(ui_web_view_t *v){ULONGLONG begin=GetTickCount64();int r=0,n=0;do{pump();ui_webview2_view_get_state(v,&r,&n);if(r&&n)break;}while(GetTickCount64()-begin<15000);check(r&&n,"ready within existing 15s");state("ready",v);}
static void drain(void){ULONGLONG begin=GetTickCount64();while(pending()&&GetTickCount64()-begin<15000)pump();check(!pending(),"all cleanup completes within existing 15s");state("drained",NULL);}
static void callback(ui_status_t s,const char *json,void *unused){(void)unused;++callbacks;if(closed)++invalid_callbacks;printf("CALLBACK tick=%llu status=%d closed=%d result=%s\n",GetTickCount64(),s,closed,json?json:"null");}
int main(void){HWND root;ui_host_config_t hc={0};ui_webview2_backend_config_t cfg={0};ui_host_t *host;ui_web_backend_t *backend;ui_web_view_t *view;ui_status_t s;DWORD handles=0,gdi,users,end=0;setvbuf(stdout,NULL,_IONBF,0);runtime_diagnostics_initialize();check(SUCCEEDED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)),"COM");check(ui_framework_initialize()==UI_STATUS_OK,"initialize");root=CreateWindowW(L"STATIC",L"P5 PUBLIC RUNTIME BOUNDARIES",WS_OVERLAPPEDWINDOW,80,80,500,320,NULL,NULL,GetModuleHandleW(NULL),NULL);hc.size=sizeof(hc);hc.api_version=UI_FRAMEWORK_API_VERSION;hc.native_parent=root;host=ui_host_create(&hc);cfg.size=sizeof(cfg);cfg.framework_components=1;GetProcessHandleCount(GetCurrentProcess(),&handles);gdi=GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS);users=GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS);state("initial",NULL);
 backend=ui_webview2_backend_create(&cfg,&s);check(backend&&s==UI_STATUS_OK,"normal warm baseline");view=ui_web_view_create(host,backend);check(view!=NULL,"warm view");check(ui_web_view_load_html(view,"<p>Warm baseline</p>")==UI_STATUS_OK,"warm document");ready(view);ui_web_view_destroy(view);ui_webview2_backend_destroy(backend);drain();GetProcessHandleCount(GetCurrentProcess(),&handles);gdi=GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS);users=GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS);state("warmed-budget-baseline",NULL);
 backend=ui_webview2_backend_create(&cfg,&s);check(backend&&s==UI_STATUS_OK,"create pending backend");view=ui_web_view_create(host,backend);check(view!=NULL,"create pending view");check(ui_web_view_load_html(view,"<p id='pending'>PENDING permitted</p>")==UI_STATUS_OK,"load during creation");state("close-before-first-pump",view);ui_web_view_destroy(view);state("pending-view-destroy-return",NULL);ui_webview2_backend_destroy(backend);state("pending-backend-destroy-return",NULL);
 backend=ui_webview2_backend_create(&cfg,&s);check(backend&&s==UI_STATUS_OK,"recreate while old cleanup permitted");view=ui_web_view_create(host,backend);check(view!=NULL,"new view");check(ui_web_view_load_html(view,"<p id='ready'>Ready control</p>")==UI_STATUS_OK,"new document");ready(view);closed=0;check(ui_webview2_view_execute_script(view,"({readyControl:true})",callback,NULL)==UI_STATUS_OK,"normal request");{ULONGLONG begin=GetTickCount64();while(!callbacks&&GetTickCount64()-begin<5000)pump();check(callbacks==1,"normal callback completes");}state("normal-callback",view);check(ui_webview2_view_execute_script(view,"({cancelledRequest:true})",callback,NULL)==UI_STATUS_OK,"accepted request before destroy");state("request-before-view-destroy",view);closed=1;ui_web_view_destroy(view);state("view-destroy-cancels-callback",NULL);ui_webview2_backend_destroy(backend);state("backend-destroy",NULL);drain();check(callbacks==1&&!invalid_callbacks,"no late application callback after destroy");ui_host_destroy(host);DestroyWindow(root);GetProcessHandleCount(GetCurrentProcess(),&end);printf("RESOURCE initial=%lu final=%lu GDI=%lu,%lu USER=%lu,%lu pending=%d\n",handles,end,gdi,GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS),users,GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS),pending());check(end<=handles+12&&GetGuiResources(GetCurrentProcess(),GR_GDIOBJECTS)<=gdi+4&&GetGuiResources(GetCurrentProcess(),GR_USEROBJECTS)<=users+4,"original +12 handles/+4 GUI budgets");CoUninitialize();printf("FINAL failures=%d\n",failures);return failures?1:0;}
