/* Real host + unchanged API7 application DLL, both component providers. */
#define UI_HOST_TEST 1
#include "../examples/framework_host/main.c"
static int failures;
#define CHECK(x) do { if(!(x)){fprintf(stderr,"visual line%d: %s\n",__LINE__,#x);++failures;} } while(0)
static void pump(DWORD ms)
{ULONGLONG end=GetTickCount64()+ms;do{MSG m;unsigned n=0;while(n++<1000&&PeekMessageW(&m,NULL,0,0,PM_REMOVE))if(m.message!=WM_QUIT){TranslateMessage(&m);DispatchMessageW(&m);}Sleep(1);}while(GetTickCount64()<end);}
static ui_status_t presentation(ui_component_t *c,const char *id,ui_element_presentation_t *p)
{ULONGLONG end=GetTickCount64()+10000;ui_status_t status;do{status=ui_component_get_presentation(c,id,p);if(status!=UI_STATUS_PENDING)return status;pump(1);}while(GetTickCount64()<end);return status;}
static int press(ui_web_view_t *v,const char *id)
{ui_element_presentation_t p={0};ui_input_event_t e={0};p.size=sizeof(p);if(ui_web_view_get_presentation(v,id,&p)!=UI_STATUS_OK||!p.visible||!p.enabled)return 0;e.size=sizeof(e);e.pointer_button=1;e.x=p.clip.x+p.clip.width/2;e.y=p.clip.y+p.clip.height/2;e.kind=UI_INPUT_POINTER_DOWN;if(ui_web_view_dispatch_input(v,&e)!=UI_STATUS_OK)return 0;e.kind=UI_INPUT_POINTER_UP;return ui_web_view_dispatch_input(v,&e)==UI_STATUS_OK;}

static int component_press(ui_component_t *c,const char *id)
{ui_element_presentation_t p={0};ui_input_event_t e={0};p.size=sizeof(p);if(presentation(c,id,&p)!=UI_STATUS_OK||!p.visible||!p.enabled)return 0;e.size=sizeof(e);e.pointer_button=1;e.x=p.clip.x+p.clip.width/2;e.y=p.clip.y+p.clip.height/2;e.kind=UI_INPUT_POINTER_DOWN;if(ui_component_dispatch_input(c,&e)!=UI_STATUS_OK)return 0;pump(20);e.kind=UI_INPUT_POINTER_UP;if(ui_component_dispatch_input(c,&e)!=UI_STATUS_OK)return 0;pump(30);return 1;}
static void save_bmp(const wchar_t *prefix,const wchar_t *name,const void *bits,int width,int height)
{wchar_t path[4096];FILE *f=NULL;BITMAPFILEHEADER file={0};BITMAPINFOHEADER info={0};if(!prefix)return;swprintf(path,4096,L"%s-%s.bmp",prefix,name);file.bfType=0x4d42;file.bfOffBits=sizeof(file)+sizeof(info);file.bfSize=file.bfOffBits+(DWORD)width*(DWORD)height*4;info.biSize=sizeof(info);info.biWidth=width;info.biHeight=-height;info.biPlanes=1;info.biBitCount=32;CHECK(!_wfopen_s(&f,path,L"wb"));if(f){CHECK(fwrite(&file,sizeof(file),1,f)==1);CHECK(fwrite(&info,sizeof(info),1,f)==1);CHECK(fwrite(bits,4,(size_t)width*height,f)==(size_t)width*height);fclose(f);}}
static void host_frame(HWND hwnd,const wchar_t *prefix,const wchar_t *name)
{RECT r;HDC dc;HBITMAP bmp;HGDIOBJ old;BITMAPINFO info={0};void *bits;GetWindowRect(hwnd,&r);r.right-=r.left;r.bottom-=r.top;dc=CreateCompatibleDC(NULL);info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=r.right;info.bmiHeader.biHeight=-r.bottom;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;bmp=CreateDIBSection(dc,&info,DIB_RGB_COLORS,&bits,NULL,0);CHECK(bmp!=NULL);if(bmp){old=SelectObject(dc,bmp);CHECK(PrintWindow(hwnd,dc,2));GdiFlush();save_bmp(prefix,name,bits,r.right,r.bottom);SelectObject(dc,old);DeleteObject(bmp);}DeleteDC(dc);}
static unsigned background(ui_component_t *c,const wchar_t *prefix,const wchar_t *name,uint32_t dpi,int height)
{ui_pixel_buffer_t p={0};ui_status_t status;ULONGLONG end;unsigned color=0;p.size=sizeof(p);CHECK(ui_component_capture_rgba(c,480,height,dpi,&p)==UI_STATUS_OK);p.capacity=p.stride*p.height;p.pixels=(uint8_t *)malloc(p.capacity);CHECK(p.pixels!=NULL);if(!p.pixels)return 0;end=GetTickCount64()+10000;do{status=ui_component_capture_rgba(c,480,height,dpi,&p);if(status!=UI_STATUS_PENDING)break;pump(1);}while(GetTickCount64()<end);CHECK(status==UI_STATUS_OK);if(status==UI_STATUS_OK){size_t at=p.stride*2+2*4;color=((unsigned)p.pixels[at]<<16)|((unsigned)p.pixels[at+1]<<8)|p.pixels[at+2];for(size_t i=0;i<p.capacity;i+=4){uint8_t red=p.pixels[i];p.pixels[i]=p.pixels[i+2];p.pixels[i+2]=red;}save_bmp(prefix,name,p.pixels,p.width,p.height);}free(p.pixels);return color;}
static unsigned pixel(ui_web_view_t *v,int x,int y)
{ui_pixel_buffer_t p={0};unsigned color=0;p.size=sizeof(p);CHECK(ui_web_view_capture_rgba(v,160,100,96,&p)==UI_STATUS_OK);p.capacity=p.stride*p.height;p.pixels=malloc(p.capacity);CHECK(p.pixels!=NULL);if(p.pixels){CHECK(ui_web_view_capture_rgba(v,160,100,96,&p)==UI_STATUS_OK);size_t at=p.stride*(size_t)y+(size_t)x*4;color=((unsigned)p.pixels[at]<<16)|((unsigned)p.pixels[at+1]<<8)|p.pixels[at+2];free(p.pixels);}return color;}
static void renderer_states(ui_host_t *h)
{ui_light_web_config_t config={sizeof(config)};ui_web_backend_t *backend=ui_light_web_backend_create(&config);ui_web_view_t *v=ui_web_view_create(h,backend);ui_input_event_t e={0};
 CHECK(v!=NULL);if(!v)return;CHECK(ui_web_view_load_html(v,"<style>body{margin:0;background:#ffffff}#cell{height:30px;width:100px;border:1px solid #dddddd}button{height:30px;width:100px;border:0;background:#ffffff}button:active{background:#123456}</style><body><div id='cell'>Visible cell</div><button id='press'>Action</button><div class='glyph' style='font-family:Segoe MDL2 Assets'>\xEE\x9C\x8D</div></body>")==UI_STATUS_OK);
 CHECK(pixel(v,80,15)==0xffffff);e.size=sizeof(e);e.pointer_button=1;e.x=80;e.y=45;e.kind=UI_INPUT_POINTER_DOWN;CHECK(ui_web_view_dispatch_input(v,&e)==UI_STATUS_OK);CHECK(pixel(v,80,45)==0x123456);e.kind=UI_INPUT_CANCEL;CHECK(ui_web_view_dispatch_input(v,&e)==UI_STATUS_OK);CHECK(pixel(v,80,45)==0xffffff);ui_web_view_destroy(v);ui_light_web_backend_destroy(backend);}

static void polish_geometry(ui_component_t *table,ui_component_t *form,ui_component_t *viewport)
{ui_element_presentation_t label={0},input={0},image={0},title={0},header={0},cell={0};label.size=input.size=image.size=title.size=header.size=cell.size=sizeof(label);
 CHECK(presentation(form,"title",&title)==UI_STATUS_OK&&!title.visible);
 CHECK(presentation(form,"label-name",&label)==UI_STATUS_OK&&label.visible);CHECK(presentation(form,"field-name",&input)==UI_STATUS_OK&&input.visible);
 CHECK(label.clip.width>=72&&input.clip.width>=100&&abs(label.rect.y-input.rect.y)<=1&&input.rect.x>=label.rect.x+label.rect.width);
 CHECK(presentation(viewport,"controls",&title)==UI_STATUS_OK&&!title.visible);CHECK(presentation(viewport,"preview-pixels",&image)==UI_STATUS_OK&&image.visible&&image.clip.width>=120&&image.clip.height==image.clip.width);
 CHECK(presentation(table,"sort-name",&header)==UI_STATUS_OK);CHECK(presentation(table,"cell-9007199254741000-name",&cell)==UI_STATUS_OK);printf("Header/content: %d,%d versus %d,%d\n",header.rect.x,header.rect.width,cell.rect.x,cell.rect.width);CHECK(header.rect.x==cell.rect.x&&header.rect.width==cell.rect.width);
}
int wmain(int argc,wchar_t **argv)
{host_window_t h={0};HWND root;ui_app_instance_info_t info={0};ui_component_t *table,*form,*tree;ui_component_state_t state={0};ui_element_presentation_t p={0};ui_cell_t value={0};ui_rect_t before,after;uint64_t first,second,target;const wchar_t *prefix=argc>4?argv[4]:NULL;int baseline=argc>5&&!wcscmp(argv[5],L"--baseline");wchar_t provider[4096];
 if(argc<4)return 2;setvbuf(stdout,NULL,_IONBF,0);CHECK(SUCCEEDED(CoInitializeEx(NULL,COINIT_APARTMENTTHREADED)));CHECK(ui_framework_initialize()==UI_STATUS_OK);CHECK(GetFullPathNameW(argv[2],4096,provider,NULL)>0);SetEnvironmentVariableW(L"UI_API7_OSMESA_DLL",provider);SetEnvironmentVariableW(L"UI_API7_BACKEND",argv[3]);root=create_host(&h,GetModuleHandleW(NULL));CHECK(root!=NULL);if(!root)return 1;ShowWindow(root,SW_SHOW);ShowWindow(root,SW_SHOW);CHECK(IsWindowVisible(root));SetWindowPos(root,HWND_TOPMOST,40,40,1200,800,0);pump(40);
 CHECK(!assistant_visible(&h));if(!baseline)renderer_states(h.chrome_host);if(prefix)host_frame(root,prefix,L"empty");open_path(&h,argv[1]);pump(500);first=ui_workspace_active(h.workspace);open_path(&h,argv[1]);pump(500);second=ui_workspace_active(h.workspace);CHECK(first&&second&&first!=second);CHECK(get_instance(&h,second,&info));if(!info.host){fprintf(stderr,"Load: %s\n",ui_workspace_last_error(h.workspace));return 1;}table=ui_component_find(info.host,"table");form=ui_component_find(info.host,"form");tree=ui_component_find(info.host,"tree");CHECK(table&&form&&tree);if(!table||!form||!tree)return 1;
 state.size=sizeof(state);CHECK(ui_component_get_state(table,&state)==UI_STATUS_OK&&state.total_count==100000&&state.rendered_nodes<1024);CHECK(ui_component_select(table,9007199254741001ULL)==UI_STATUS_OK);value.size=sizeof(value);value.kind=UI_VALUE_TEXT;value.text="Unsaved draft";value.flags=UI_VALUE_MODIFIED;CHECK(ui_component_set_field(form,"name",&value)==UI_STATUS_OK);CHECK(ui_component_set_error(form,"name","Validation feedback") ==UI_STATUS_OK);p.size=sizeof(p);CHECK(presentation(table,"scroll-v-thumb",&p)==UI_STATUS_OK&&p.visible);CHECK(presentation(form,"field-name",&p)==UI_STATUS_OK&&p.visible);
 for(int dark=0;dark<2;++dark){h.dark=dark;layout(&h);pump(120);for(uint32_t dpi=96;dpi<=192;dpi+=48){wchar_t name[80];swprintf(name,80,L"table-%s-%u",dark?L"dark":L"light",dpi);unsigned color=background(table,prefix,name,dpi,320);if(!baseline){CHECK(dark?color<0x808080:color>0xc0c0c0);CHECK(presentation(table,"controls",&p)==UI_STATUS_OK&&!p.visible);CHECK(presentation(table,"next-page",&p)==UI_STATUS_NOT_FOUND);CHECK(presentation(table,"rows",&p)==UI_STATUS_OK&&p.rect.y<=76&&p.rect.height>=180);}layout(&h);pump(50);}if(!baseline)polish_geometry(table,form,ui_component_find(info.host,"viewport"));if(prefix){host_frame(root,prefix,dark?L"host-dark":L"host-light");background(form,prefix,dark?L"form-dark":L"form-light",96,320);background(tree,prefix,dark?L"tree-dark":L"tree-light",96,320);layout(&h);pump(50);}}

 for(uint32_t dpi=96;dpi<=192;dpi+=48){h.dpi=dpi;MoveWindow(root,40,40,MulDiv(1200,(int)dpi,96),MulDiv(800,(int)dpi,96),TRUE);layout(&h);pump(80);const char *ids[]={"recent","open","assistant-toggle","window-min","window-max","window-close"};for(size_t i=0;i<6;++i){CHECK(ui_web_view_get_presentation(h.view,ids[i],&p)==UI_STATUS_OK&&p.visible&&p.clip.width==p.rect.width);}if(prefix){wchar_t name[80];swprintf(name,80,L"host-dpi-%u",dpi);host_frame(root,prefix,name);}}
 h.dpi=GetDpiForWindow(root);MoveWindow(root,40,40,1200,800,TRUE);layout(&h);pump(30);
 h.dark=0;layout(&h);pump(20);target=h.target;CHECK(ui_web_view_get_element_rect(h.view,"workspace",&before)==UI_STATUS_OK);CHECK(press(h.view,"assistant-toggle"));pump(30);CHECK(assistant_visible(&h)&&h.target==target);CHECK(ui_web_view_get_element_rect(h.view,"workspace",&after)==UI_STATUS_OK&&after.width<before.width);if(!baseline){CHECK(ui_web_view_get_presentation(h.view,"schema",&p)==UI_STATUS_OK&&!p.visible);CHECK(press(h.view,"advanced-toggle"));pump(30);CHECK(ui_web_view_get_presentation(h.view,"schema",&p)==UI_STATUS_OK&&p.visible);CHECK(press(h.view,"advanced-toggle"));pump(30);}if(prefix)host_frame(root,prefix,L"assistant");CHECK(press(h.view,"assistant-toggle"));pump(30);CHECK(ui_web_view_get_element_rect(h.view,"workspace",&after)==UI_STATUS_OK&&after.width==before.width);
 
 value.kind=UI_VALUE_COLOR;value.text="#4080bfff";value.flags=0;CHECK(ui_component_set_field(form,"color",&value)==UI_STATUS_OK);CHECK(component_press(form,"color-color"));if(prefix)background(form,prefix,L"color-picker",96,640);{ui_input_event_t e={0};e.size=sizeof(e);e.kind=UI_INPUT_KEY_DOWN;e.key_code=VK_ESCAPE;CHECK(ui_component_dispatch_input(form,&e)==UI_STATUS_OK);}layout(&h);pump(30);CHECK(component_press(form,"choice-mode"));if(prefix)background(form,prefix,L"enum",96,480);{ui_input_event_t e={0};e.size=sizeof(e);e.kind=UI_INPUT_KEY_DOWN;e.key_code=VK_ESCAPE;CHECK(ui_component_dispatch_input(form,&e)==UI_STATUS_OK);}layout(&h);pump(30);
 CHECK(ui_workspace_activate(h.workspace,first)==UI_STATUS_OK);CHECK(ui_workspace_activate(h.workspace,second)==UI_STATUS_OK);layout(&h);pump(40);CHECK(!assistant_visible(&h)&&h.target==target);CHECK(ui_component_get_field(form,"name",&value)==UI_STATUS_OK&&!strcmp(value.text,"Unsaved draft"));MoveWindow(root,40,40,320,600,TRUE);layout(&h);pump(60);if(prefix)host_frame(root,prefix,L"narrow");CHECK(press(h.view,"tab-more"));pump(20);CHECK(h.popup_kind==1);close_popup(&h);
 SendMessageW(root,WM_CLOSE,0,0);for(int i=0;i<1000&&IsWindow(root);++i)pump(10);CHECK(!IsWindow(root));pump(500);printf("Visual actual %ls DLL / OSMesa / dual instance: %d failures\n",argv[3],failures);CoUninitialize();return failures?1:0;
}
