from pathlib import Path
import json
root=Path.cwd(); items=json.loads((root/'build/language-20261008/text-inventory.json').read_text(encoding='utf-8'))
english=[
'\n… (display truncated)\n','\nParameters:',' (mixed values)',' · Closing',' · Loading',' · Image failed',' columns',' items','C Application Framework · Web','☐ No','☑ Yes',
'Previous tab · Ctrl+Shift+Tab','Previous page','Next tab · Ctrl+Tab','Next page','Your application workspace','Keep color','Allow','Allow the assistant to run this operation?','Close','Close host','Close current tab · Ctrl+W','Switch light / dark theme','Loading','Loading · ','Assistant workspace','Raw parameters · JSON','Raw parameters are not valid JSON. Correct them in Advanced.','Parameter definition · JSON schema','Parameters exceed the current 4095 UTF-8 byte input limit.','Cancel','Cancel task','Combined parameters exceed 4095 UTF-8 bytes. Shorten the input or use Advanced.','No','Roll back','Failed','Full content · Close','Host options','Host options: theme, layout and window actions','No open tabs','No successfully opened applications','No records','Tools','Application #%llu: %s. See Advanced for details.','Application #%llu: running %d%%','Application packages (*.uapp)\0*.uapp\0\0','Application menus are below the tab bar','Begin','Open tabs','Required field','Open .uapp package · Ctrl+Shift+O','Open a .uapp package and switch between tabs. Applications choose native, OpenGL or Web content.','Open application package','Open package · Ctrl+Shift+O','Open package… · Ctrl+Shift+O','Run operation','Execution status','Submit','Notice','Undo','Undo color','Operation completed','Operation not completed','Yes','Show or hide the assistant workspace','None','No items','More ▾','Maximize / Restore','Minimize','Recently opened applications','Recently opened applications (separate from open tabs)','View state snapshot','Loading…','Configure this parameter in Advanced; existing values are retained.','This operation needs no parameters.','Light / dark theme','Mixed','Switching tabs does not change the target.','Target instance','Target instance #%llu\nCommand:','Menu','Detailed results / progress / events','Semantic command','Enter a valid number','Enter a valid number.','Choose a valid option','Calls the fixed target instance; switching tabs does not change the task target.','Exit','Fit header and loaded content','Choose','Choose assistant target instance','Choose command','Choose application','Choose operation','Choose a target and operation to run.','Choose semantic command','Reset all column widths','Reset active application layout','Reset this column width','Color format is #RRGGBB or #RRGGBBAA','Advanced: parameters, transactions and details ▸','Advanced: parameters, transactions and details ▾']
assert len(items)==len(english),(len(items),len(english))
pairs=[(item['zh'],item['zh'],en) for item,en in zip(items,english) if '\0' not in item['zh']]
pairs += [('Dock','停靠','Dock')]
def quoted(value): return json.dumps(value,ensure_ascii=False)
path=root/'src/language_catalog.inc'
path.write_text('/* Immutable framework-owned text resources. Application data is never looked up here. */\n'+'\n'.join('UI_TEXT('+','.join(quoted(s) for s in row)+')' for row in pairs)+'\n',encoding='utf-8')
print('Central framework catalog',len(pairs))
