#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <imm.h>
#include <GL/gl.h>
#include <psapi.h>
#include <tlhelp32.h>
#include "ui_framework/images.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "ui_framework/application.h"
#include "ui_framework/components.h"
#include "ui_framework/package.h"
#include "ui_framework/shell.h"
#include "klayoutc/core.h"
#include "klayoutc/render.h"
#include "klayoutc/app_diagnostics.h"
#include "ui_framework/menus.h"
#include "regression_version.h"
/* This framework-owned observer is rebuilt against the current source override. */
#undef KC_REGRESSION_SDK_COMMIT
#define KC_REGRESSION_SDK_COMMIT "807828147bdfb6959abb49b4668dfa90c34eda56"
_Static_assert(UI_FRAMEWORK_API_VERSION==KC_REGRESSION_API,"locked headers match recorded API");

/* Application-owned integration tests use only the published SDK. */
typedef struct test_state {ui_workspace_t *workspace;uint64_t instance,request;int success;unsigned results;char result[2048];} test_state_t;
static unsigned failures,checks;
static int offscreen_mode;
static int input_trace;
static const uint32_t expected_api=KC_REGRESSION_API;
static ui_surface_t *offscreen_canvas(ui_host_t *host)
{union{FARPROC proc;kc_offscreen_canvas_fn get;}symbol;symbol.proc=GetProcAddress(GetModuleHandleW(L"klayoutc_app.dll"),"klayoutc_get_offscreen_canvas_v1");ui_surface_t *surface=NULL;if(symbol.proc)(void)symbol.get(host,&surface);return surface;}
static int render_offscreen(ui_host_t *host,ui_pixel_buffer_t *pixels)
{ui_surface_t *surface=offscreen_canvas(host);if(!surface)return 0;memset(pixels,0,sizeof(*pixels));pixels->size=sizeof(*pixels);if(ui_opengl_offscreen_render(surface,pixels)!=UI_STATUS_OK)return 0;pixels->capacity=pixels->stride*pixels->height;pixels->pixels=malloc(pixels->capacity);return pixels->pixels && ui_opengl_offscreen_render(surface,pixels)==UI_STATUS_OK;}
static void check(int ok,const char *text){++checks;if(!ok)++failures;fprintf(stderr,"%s: %s\n",ok?"PASS":"FAIL",text);fflush(stderr);}
static void result_received(uint64_t id,const ui_result_t *result,void *data){test_state_t *t=data;++t->results;t->instance=id;t->request=result->request_id;t->success=result->success;(void)snprintf(t->result,sizeof(t->result),"%s",result->result_json?result->result_json:"");}
static int approve(uint64_t id,const char *command,const char *json,ui_assistant_permission_t permission,void *data){(void)id;(void)command;(void)json;(void)permission;(void)data;return 1;}
static LRESULT CALLBACK window_proc(HWND hwnd,UINT message,WPARAM wp,LPARAM lp){ui_workspace_t *w=(ui_workspace_t *)GetWindowLongPtrW(hwnd,GWLP_USERDATA);intptr_t result;if(w && ui_workspace_handle_message(w,hwnd,message,(uintptr_t)wp,(intptr_t)lp,&result)==UI_STATUS_OK)return (LRESULT)result;return DefWindowProcW(hwnd,message,wp,lp);}
static int menu_message(test_state_t *t,const MSG *message)
{
    if(message->message!=WM_KEYDOWN && message->message!=WM_KEYUP && message->message!=WM_SYSKEYDOWN && message->message!=WM_SYSKEYUP)return 0;
    HIMC ime=ImmGetContext(message->hwnd);int composing=ime && ImmGetCompositionStringW(ime,GCS_COMPSTR,NULL,0)>0;if(ime)ImmReleaseContext(message->hwnd,ime);if(composing)return 0;
    ui_app_instance_info_t i={0};i.size=sizeof(i);if(ui_workspace_get_instance(t->workspace,ui_workspace_active(t->workspace),&i)!=UI_STATUS_OK)return 0;
    ui_input_event_t e={0};e.size=sizeof(e);e.kind=message->message==WM_KEYDOWN || message->message==WM_SYSKEYDOWN?UI_INPUT_KEY_DOWN:UI_INPUT_KEY_UP;e.key_code=(uint32_t)message->wParam;
    e.modifiers=(GetKeyState(VK_CONTROL)<0?UI_INPUT_MODIFIER_CONTROL:0)|(GetKeyState(VK_SHIFT)<0?UI_INPUT_MODIFIER_SHIFT:0)|(GetKeyState(VK_MENU)<0?UI_INPUT_MODIFIER_ALT:0);
    ui_status_t routed=ui_host_menu_dispatch_input(i.host,&e);if(input_trace)fprintf(stderr,"INPUT_ROUTE: time%llu message%u key%u modifiers%u hwnd%p focus%p foreground%p status%d\n",(unsigned long long)GetTickCount64(),message->message,e.key_code,e.modifiers,(void*)message->hwnd,(void*)GetFocus(),(void*)GetForegroundWindow(),routed);return routed==UI_STATUS_OK;
}
static void pump(test_state_t *t){if(offscreen_mode){for(size_t n=0;n<ui_workspace_count(t->workspace);++n){ui_app_instance_info_t i={0};i.size=sizeof(i);if(ui_workspace_get_instance(t->workspace,ui_workspace_instance_at(t->workspace,n),&i)==UI_STATUS_OK){union{FARPROC proc;kc_offscreen_poll_fn poll;}symbol;symbol.proc=GetProcAddress(GetModuleHandleW(L"klayoutc_app.dll"),"klayoutc_offscreen_poll_v1");if(symbol.proc)(void)symbol.poll(i.host);if(!i.closing){ui_pixel_buffer_t pixels={0};(void)render_offscreen(i.host,&pixels);free(pixels.pixels);}}}(void)ui_workspace_flush(t->workspace,64);return;}MSG message;while(PeekMessageW(&message,NULL,0,0,PM_REMOVE)){if(menu_message(t,&message))continue;TranslateMessage(&message);DispatchMessageW(&message);}ui_workspace_poll(t->workspace);}
static ui_app_instance_info_t info(test_state_t *t,uint64_t id){ui_app_instance_info_t i={0};i.size=sizeof(i);(void)ui_workspace_get_instance(t->workspace,id,&i);return i;}
static const char *snapshot(test_state_t *t,uint64_t id){ui_app_instance_info_t i=info(t,id);const char *s=NULL;if(i.assistant)(void)ui_assistant_get_state_snapshot(i.assistant,&s);return s?s:"{}";}
static uint64_t integer(test_state_t *t,uint64_t id,const char *key){char token[96];(void)snprintf(token,sizeof(token),"\"%s\":",key);const char *s=strstr(snapshot(t,id),token);if(!s)return UINT64_MAX;s+=strlen(token);if(*s=='"')++s;return strtoull(s,NULL,10);}
static int has(test_state_t *t,uint64_t id,const char *text){return strstr(snapshot(t,id),text)!=NULL;}
static int wait_result(test_state_t *t,uint64_t id,uint64_t request){ULONGLONG until=GetTickCount64()+15000;do{pump(t);if(t->instance==id && t->request==request)return 1;Sleep(1);}while(GetTickCount64()<until);return 0;}
static int command(test_state_t *t,uint64_t id,const char *name,const char *json,int success){uint64_t request=0;ui_status_t s;if(!strcmp(name,"klayoutc.properties_submit")||!strcmp(name,"klayoutc.properties_cancel")||!strcmp(name,"klayoutc.dialog_submit")||!strcmp(name,"klayoutc.dialog_cancel")){t->request=0;request=ui_host_invoke(info(t,id).host,name,json,"component");s=request?UI_STATUS_OK:UI_STATUS_NOT_FOUND;}else s=ui_workspace_invoke(t->workspace,id,name,json,&request);int ok=s==UI_STATUS_OK && request && wait_result(t,id,request) && t->success==success;if(!ok)fprintf(stderr,"COMMAND %s status %d result %s\n",name,s,t->result);return ok;}
static int idle(test_state_t *t,uint64_t id){ULONGLONG until=GetTickCount64()+15000;do{pump(t);if(has(t,id,"\"busy\":false") && has(t,id,"\"property_pending\":false") && integer(t,id,"generation")==integer(t,id,"rendered_generation"))return 1;Sleep(1);}while(GetTickCount64()<until);return 0;}
static ui_component_t *component(test_state_t *t,uint64_t id,const char *name){return ui_component_find(info(t,id).host,name);}
static ui_component_state_t state(ui_component_t *c){ui_component_state_t s={0};s.size=sizeof(s);(void)ui_component_get_state(c,&s);return s;}
static int field(ui_component_t *c,const char *id,ui_value_kind_t kind,const char *text,uint32_t flags){ui_cell_t v={0};v.size=sizeof(v);v.kind=kind;v.text=text;v.flags=flags;return ui_component_set_field(c,id,&v)==UI_STATUS_OK;}
static int wait_rows(test_state_t *t,ui_component_t *c,uint64_t count){ULONGLONG until=GetTickCount64()+10000;do{pump(t);if(state(c).total_count==count && state(c).row_count)return 1;Sleep(1);}while(GetTickCount64()<until);return 0;}
static HWND child(HWND root,const wchar_t *name){for(HWND h=GetWindow(root,GW_CHILD);h;h=GetWindow(h,GW_HWNDNEXT)){wchar_t actual[128];GetClassNameW(h,actual,128);if(!wcscmp(actual,name))return h;HWND found=child(h,name);if(found)return found;}return NULL;}
static void close_instance(test_state_t *t,uint64_t id){ui_status_t s=ui_workspace_close(t->workspace,id,UI_APP_CLOSE_TAB);if(s==UI_STATUS_CANCELLED){ui_component_t *d=component(t,id,"klayoutc.dialog.discard");check(d && state(d).modal,"unsaved close REFUSE exposes instance modal");(void)field(d,"p0",UI_VALUE_ENUM,"Discard",0);check(command(t,id,"klayoutc.dialog_submit","{}",1),"close confirmation dispatches through command");}ULONGLONG until=GetTickCount64()+15000;do{pump(t);if(!info(t,id).host)return;Sleep(1);}while(GetTickCount64()<until);check(0,"worker close completion unloads instance");}
static void path_json(const char *path,char *json,size_t bytes){char escaped[4096];size_t at=0;for(const char *p=path;*p && at+3<sizeof(escaped);++p){if(*p=='\\'||*p=='"')escaped[at++]='\\';escaped[at++]=*p;}escaped[at]=0;(void)snprintf(json,bytes,"{\"path\":\"%s\"}",escaped);}
static void save_fixture(test_state_t *t,uint64_t id,const char *name){char json[4608];path_json(name,json,sizeof(json));check(command(t,id,"klayoutc.save_as",json,1),"current UI saves official reread fixture");}
static void package_contract(const char *path){ui_package_t *package=NULL;char error[512];check(ui_package_open(path,&package,error,sizeof(error))==UI_STATUS_OK,"strict package parser validates actual UAPP");if(!package)return;const ui_package_metadata_t *m=ui_package_get_metadata(package);check(m && m->abi_version==1 && m->framework_api_version==expected_api && m->multiple_instances,"manifest ABI1 and unchanged declared API match expected application");int pngs=0,runtime=0;for(size_t i=0;i<ui_package_entry_count(package);++i){ui_package_entry_t entry;if(ui_package_get_entry(package,i,&entry)!=UI_STATUS_OK)continue;if(strstr(entry.name,".png"))++pngs;if(strstr(entry.name,"ui_framework.dll")||strstr(entry.name,"framework_host.exe"))++runtime;}check(pngs==6 && !runtime,"UAPP carries icons and excludes replacement framework runtime");ui_package_destroy(package);}
static void partial_mount(HWND root){HMODULE module=GetModuleHandleW(L"klayoutc_app.dll");union{FARPROC proc;ui_app_query_fn query;}symbol;symbol.proc=module?GetProcAddress(module,"ui_app_query_v1"):NULL;const ui_app_descriptor_t *api=symbol.proc?symbol.query():NULL;check(api && api->abi_version==1 && api->framework_api_version==expected_api,"actual exported descriptor agrees with manifest");if(!api)return;ui_host_config_t config={0};config.size=sizeof(config);config.api_version=UI_FRAMEWORK_API_VERSION;config.native_parent=root;ui_host_t *host=ui_host_create(&config);ui_app_context_t context={0};context.size=sizeof(context);context.abi_version=1;context.host=host;context.instance_id=UINT64_C(9007199254740993);ui_assistant_config_t assistant={0};assistant.size=sizeof(assistant);void *state=NULL;ui_status_t created=host?api->create(&context,&state,&assistant):UI_STATUS_PLATFORM_ERROR;check(created==UI_STATUS_OK && state,"partial-init probe creates real application state with public host");if(state){const char *identity=assistant.snapshot?assistant.snapshot(assistant.user_data):NULL;check(identity && strstr(identity,"\"instance_id\":\"9007199254740993\""),"real application context above 2^53 is serialized exactly");check(api->mount(state,&context)!=UI_STATUS_OK,"host without a content shell fails after partial GPU initialization");api->unmount(state);}if(host)ui_host_destroy(host);if(state)api->destroy(state);check(!child(root,L"KLayoutC.NativePane.v1"),"partial initialization follows shared native/GPU cleanup path");}
static int capture(HWND root,const wchar_t *path){RECT r;GetClientRect(root,&r);POINT origin={0,0};ClientToScreen(root,&origin);HDC dc=GetDC(NULL),memory=CreateCompatibleDC(dc);BITMAPINFO bi={0};bi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bi.bmiHeader.biWidth=r.right;bi.bmiHeader.biHeight=-r.bottom;bi.bmiHeader.biPlanes=1;bi.bmiHeader.biBitCount=32;void *pixels=NULL;HBITMAP bitmap=CreateDIBSection(dc,&bi,DIB_RGB_COLORS,&pixels,NULL,0);HGDIOBJ old=bitmap?SelectObject(memory,bitmap):NULL;int ok=bitmap && BitBlt(memory,0,0,r.right,r.bottom,dc,origin.x,origin.y,SRCCOPY|CAPTUREBLT);if(ok){BITMAPFILEHEADER head={0};head.bfType=0x4d42;head.bfOffBits=sizeof(head)+sizeof(bi.bmiHeader);head.bfSize=head.bfOffBits+(DWORD)((size_t)r.right*(size_t)r.bottom*4);FILE *f=_wfopen(path,L"wb");ok=f && fwrite(&head,sizeof(head),1,f)==1 && fwrite(&bi.bmiHeader,sizeof(bi.bmiHeader),1,f)==1 && fwrite(pixels,1,head.bfSize-head.bfOffBits,f)==head.bfSize-head.bfOffBits;if(f)fclose(f);}if(old)SelectObject(memory,old);if(bitmap)DeleteObject(bitmap);DeleteDC(memory);ReleaseDC(NULL,dc);return ok;}
static void image_contract(test_state_t *t,uint64_t id){ui_host_t *host=info(t,id).host;ui_image_stats_t before={0};before.size=sizeof(before);check(ui_image_get_stats(host,&before)==UI_STATUS_OK && before.limit==32u*1024u*1024u && before.count>=6,"package PNG resources use default 32 MiB image budget");unsigned char pixel[4]={23,50,81,127};ui_rgba_desc_t rgba={0};rgba.size=sizeof(rgba);rgba.width=rgba.height=1;rgba.stride=rgba.bytes=4;rgba.pixels=pixel;ui_image_id_t image=0;check(ui_image_create(host,&rgba,&image)==UI_STATUS_OK && image,"public straight RGBA create copies caller data");ui_image_info_t old={0},updated={0};old.size=updated.size=sizeof(old);(void)ui_image_get_info(host,image,&old);pixel[0]=99;check(ui_image_update(host,image,&rgba)==UI_STATUS_OK && ui_image_get_info(host,image,&updated)==UI_STATUS_OK && updated.version>old.version,"image update publishes a new content version");check(ui_image_release(host,image)==UI_STATUS_OK,"explicit image release stays with allocating module");size_t bytes=64u*1024u*1024u;unsigned char *large=calloc(1,bytes);if(large){rgba.width=rgba.height=4096;rgba.stride=4096*4;rgba.bytes=bytes;rgba.pixels=large;check(ui_image_create(host,&rgba,&image)==UI_STATUS_LIMIT_EXCEEDED,"oversized image is rejected without raising default budget");free(large);}else check(0,"image budget fixture allocation");}
static void queued_contract(test_state_t *t,uint64_t id,ui_component_t *tree){uint64_t generation=state(tree).generation,total=state(tree).total_count;ui_row_t row={0};row.size=sizeof(row);row.id=UINT64_C(9007199254740993);row.title="obsolete";ui_component_batch_t batch={0};batch.size=sizeof(batch);batch.component_generation=generation-1;batch.request_id=UINT64_MAX;batch.total_count=1;batch.rows=&row;batch.row_count=1;check(ui_workspace_post_component_batch(t->workspace,id,"klayoutc.cells",&batch)==UI_STATUS_OK,"old component generation posts copy without a UI pointer");for(int i=0;i<5;++i)pump(t);check(state(tree).generation==generation && state(tree).total_count==total,"late obsolete batch cannot overwrite visible project");size_t bytes=512u*512u*4u;unsigned char *pixels=calloc(1,bytes);if(!pixels){check(0,"queue budget fixture allocation");return;}ui_thumbnail_result_t thumbnail={0};thumbnail.size=sizeof(thumbnail);thumbnail.component_generation=generation-1;thumbnail.request_id=UINT64_MAX;thumbnail.item_id=row.id;thumbnail.dpi=96;thumbnail.rgba.size=sizeof(thumbnail.rgba);thumbnail.rgba.width=thumbnail.rgba.height=512;thumbnail.rgba.stride=512*4;thumbnail.rgba.bytes=bytes;thumbnail.rgba.pixels=pixels;int accepted=0,limited=0;for(int i=0;i<16;++i){ui_status_t s=ui_workspace_post_thumbnail(t->workspace,id,"klayoutc.cells",&thumbnail);if(s==UI_STATUS_OK)++accepted;else if(s==UI_STATUS_LIMIT_EXCEEDED){limited=1;break;}}free(pixels);check(accepted>0 && limited,"copied thumbnail queue enforces default 8 MiB budget");for(int i=0;i<5;++i)pump(t);ui_image_stats_t images={0};images.size=sizeof(images);check(ui_image_get_stats(info(t,id).host,&images)==UI_STATUS_OK && images.bytes<=images.limit,"discarding stale thumbnails leaves image ownership bounded");}

static int user_field(test_state_t *,uint64_t,HWND,const char *,const wchar_t *);
static int user_press_submit(test_state_t *,uint64_t);
#include "app_workflow_data.inc"
#include "app_usability.inc"
#include "app_offscreen.inc"
#include "app_hierarchy_input.inc"
#include "app_menu_input.inc"
#include "app_view_settings.inc"
#include "app_oasis_region.inc"
#include "app_table_layout_input.inc"
#include "business-scroll-observation.inc"
#include "app_advanced_input.inc"
#include "app_long_run.inc"
int wmain(int argc,wchar_t **argv)
{
    fprintf(stderr,"FRAMEWORK_IDENTITY: SDK%s API%u commit%s\n",KC_REGRESSION_SDK_VERSION,KC_REGRESSION_API,KC_REGRESSION_SDK_COMMIT);
    if(argc!=2 && (argc!=3 || (wcscmp(argv[2],L"--input") && wcscmp(argv[2],L"--offscreen") && wcscmp(argv[2],L"--hierarchy-input") && wcscmp(argv[2],L"--menu-input") && wcscmp(argv[2],L"--view-settings") && wcscmp(argv[2],L"--oasis-region") && wcscmp(argv[2],L"--table-layout") && wcscmp(argv[2],L"--workspace-input") && wcscmp(argv[2],L"--workspace-profile") && wcscmp(argv[2],L"--workspace-profile-reset") && wcscmp(argv[2],L"--advanced-layout") && wcscmp(argv[2],L"--auto-long"))))return 2;int bytes=WideCharToMultiByte(CP_UTF8,0,argv[1],-1,NULL,0,NULL,NULL);char *package=malloc((size_t)bytes);if(!package)return 2;WideCharToMultiByte(CP_UTF8,0,argv[1],-1,package,bytes,NULL,NULL);
    if(argc==3 && !wcscmp(argv[2],L"--offscreen")){int result=offscreen_main(package);free(package);return result;}
    if(argc==3 && (!wcscmp(argv[2],L"--workspace-profile") || !wcscmp(argv[2],L"--workspace-profile-reset"))){int result=workspace_profile_child(package,!wcscmp(argv[2],L"--workspace-profile-reset"));free(package);return result;}
    wchar_t profile[128];swprintf_s(profile,128,L"workspace-profile-%lu",GetCurrentProcessId());SetEnvironmentVariableW(L"KC_WORKSPACE_LAYOUT_DIRECTORY",profile);
    package_contract(package);test_state_t t={0};WNDCLASSW wc={0};wc.lpfnWndProc=window_proc;wc.hInstance=GetModuleHandleW(NULL);wc.hbrBackground=GetSysColorBrush(COLOR_WINDOW);wc.lpszClassName=L"KLayoutC.Regression.Test";
    check(ui_framework_initialize()==UI_STATUS_OK,"initialize published SDK");check(RegisterClassW(&wc)!=0,"register application-owned test window");HWND root=CreateWindowW(wc.lpszClassName,L"KLayout C application regression",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,20,20,1200,850,NULL,NULL,wc.hInstance,NULL);
    ui_workspace_config_t config={0};config.size=sizeof(config);config.native_parent=root;config.user_data=&t;config.result=result_received;config.confirm=approve;config.max_permission=UI_ASSISTANT_PERMISSION_EDIT;config.shell_mode=UI_WORKSPACE_SHELL_WEB;t.workspace=ui_workspace_create(&config);check(t.workspace!=NULL,"create matching public WEB workspace");if(!t.workspace){DestroyWindow(root);free(package);return 1;}
    SetWindowLongPtrW(root,GWLP_USERDATA,(LONG_PTR)t.workspace);ui_rect_t rect={0,0,1180,790};(void)ui_workspace_set_rect(t.workspace,&rect,96);ShowWindow(root,SW_SHOWNORMAL);
    uint64_t first=0,second=0;check(ui_workspace_open(t.workspace,package,&first)==UI_STATUS_OK,"load real current DLL/package");if(!first){fprintf(stderr,"LOAD %s\n",ui_workspace_last_error(t.workspace));goto cleanup;}check(ui_workspace_open(t.workspace,package,&second)==UI_STATUS_OK && second!=first,"load second isolated instance");check(ui_workspace_activate(t.workspace,first)==UI_STATUS_OK && idle(&t,first),"activate first and complete OpenGL frame");
    (void)activate_test_window(&t,root);
    if(argc==3){if(!wcscmp(argv[2],L"--auto-long"))long_run(&t,first,second,root,package);else if(!wcscmp(argv[2],L"--advanced-layout"))advanced_input(&t,first,root);else if(!wcscmp(argv[2],L"--hierarchy-input"))hierarchy_input(&t,first,root);else if(!wcscmp(argv[2],L"--menu-input"))menu_input(&t,first,root);else if(!wcscmp(argv[2],L"--view-settings"))view_settings_input(&t,first,root);else if(!wcscmp(argv[2],L"--workspace-input"))workspace_input(&t,first,root);else if(!wcscmp(argv[2],L"--table-layout"))table_layout_input(&t,first,root);else if(!wcscmp(argv[2],L"--oasis-region"))oasis_region_input(&t,first,root);else usability_input(&t,first,root);goto cleanup;}
    partial_mount(root);ui_component_t *tree=component(&t,first,"klayoutc.cells"),*layers=component(&t,first,"klayoutc.layers"),*form=component(&t,first,"klayoutc.properties");check(tree && layers && form,"public TREE TABLE FORM registered");check(!child(info(&t,first).native_container,L"SysTreeView32") && !child(info(&t,first).native_container,L"SysListView32") && !child(info(&t,first).native_container,L"KLayoutC.NativePane.v1"),"application native business controls removed");check(child(info(&t,first).native_container,L"UiFrameworkSurface")!=NULL,"renderer mounted in real content slot");
    check(wait_rows(&t,tree,1) && wait_rows(&t,layers,1),"asynchronous visible root and layer pages arrive");
    check(command(&t,first,"klayoutc.add_box","{\"x1\":0,\"y1\":0,\"x2\":100,\"y2\":80}",1),"create geometry using canonical command");uint64_t shape=integer(&t,first,"selected_id");keyboard_contract(&t,first,root);check(shape!=0 && shape!=UINT64_MAX,"stable shape identity is decimal string");check(strstr(snapshot(&t,first),"\"generation\":\"") && strstr(snapshot(&t,first),"\"instance_id\":\""),"64-bit snapshot identities use JSON strings");
    check(command(&t,first,"klayoutc.select","{\"shape\":\"9007199254740993\"}",0),"ID above 2^53 takes exact integer parsing and rejects missing object");check(integer(&t,first,"shapes")==1 && integer(&t,second,"shapes")==0,"failed identity lookup leaves model and other instance intact");
    char select_json[96];(void)snprintf(select_json,sizeof(select_json),"{\"shape\":\"%llu\"}",(unsigned long long)shape);check(command(&t,first,"klayoutc.select",select_json,1) && idle(&t,first),"select original stable object");check(field(form,"dx",UI_VALUE_NUMBER,"0.025",UI_VALUE_MODIFIED),"public draft field input for move");check(command(&t,first,"klayoutc.cell_new","{\"name\":\"CHILD\"}",1),"navigation may change draft target");
    check(strstr(ui_host_status_text(info(&t,first).host),"bound to TOP")!=NULL,"property target remains explicit after navigation");check(command(&t,first,"klayoutc.properties_submit","{}",1),"unrelated Cell creation permits submit to pinned original target");ui_cell_t draft={0};draft.size=sizeof(draft);(void)ui_component_get_field(form,"dx",&draft);check(!(draft.flags&UI_VALUE_MODIFIED) && integer(&t,first,"selection_count")==0,"successful draft accepts and preserves current navigation selection");
    (void)ui_component_accept_fields(form);check(command(&t,first,"klayoutc.properties_cancel","{}",1),"cancel transport rebinds current target");
    check(command(&t,first,"klayoutc.add_text","{\"x\":0,\"y\":0,\"text\":\"child\"}",1),"create child text");check(command(&t,first,"klayoutc.add_path","{\"points\":[[0,0],[60,40]],\"width\":8}",1),"create child path");check(command(&t,first,"klayoutc.cell","{\"name\":\"TOP\"}",1),"return via canonical Cell command");check(command(&t,first,"klayoutc.instance_add","{\"child\":\"CHILD\",\"x\":150,\"y\":80,\"angle\":37,\"mirror\":1,\"columns\":3,\"rows\":2,\"column_x\":150.5,\"column_y\":20.25,\"row_x\":-20.5,\"row_y\":140.5}",1),"place compact skew array with fractional steps");
    check(command(&t,first,"klayoutc.descend","{}",1) && has(&t,first,"\"edit_context\":true"),"array context descent");check(strstr(ui_host_status_text(info(&t,first).host),"TOP[0,0] > CHILD")!=NULL,"public status preserves hierarchy breadcrumb and array element context");check(command(&t,first,"klayoutc.add_box","{\"x1\":10,\"y1\":10,\"x2\":30,\"y2\":25}",1),"edit shared child in context");check(command(&t,first,"klayoutc.ascend","{}",1),"return parent context");
    check(command(&t,first,"klayoutc.selection_all","{}",1) && integer(&t,first,"selection_count")==2,"mixed shape and array selection");check(command(&t,first,"klayoutc.move","{\"dx\":10,\"dy\":-20}",1) && command(&t,first,"klayoutc.undo","{}",1) && command(&t,first,"klayoutc.redo","{}",1),"batch move one history step with undo redo");
    check(command(&t,first,"klayoutc.selection_all","{}",1) && command(&t,first,"klayoutc.copy","{}",1),"independent clipboard snapshot");settle(&t,100);check(command(&t,second,"klayoutc.paste_in_place","{}",1),"cross-document paste through canonical pipeline");check(integer(&t,second,"cells")==2 && integer(&t,second,"selection_count")==2,"pasted hierarchy retains compact sharing");
    check(ui_workspace_activate(t.workspace,first)==UI_STATUS_OK && idle(&t,first),"switch back preserves document and renderer");save_fixture(&t,first,"workflow-editor.gds");save_fixture(&t,second,"workflow-paste.gds");
    check(command(&t,first,"klayoutc.cell_new","{\"name\":\"LEFT\"}",1) && command(&t,first,"klayoutc.instance_add","{\"child\":\"CHILD\"}",1),"second parent sharing same child");check(idle(&t,first),"complete hierarchy edit before modal");
    image_contract(&t,first);check(wait_rows(&t,tree,2),"shared hierarchy root page updates incrementally");save_query_contract(&t,first,tree);
    uint64_t top_node=UINT64_C(1)<<32,left_node=(UINT64_C(1)<<32)|2;check(ui_component_expand(tree,top_node,1)==UI_STATUS_OK && ui_component_query(tree,top_node,0,32,0,0)==UI_STATUS_OK,"query only expanded TOP children");ULONGLONG tree_until=GetTickCount64()+5000;while(state(tree).cached_rows<3 && GetTickCount64()<tree_until){pump(&t);Sleep(1);}check(ui_component_select(tree,(UINT64_C(2)<<32)|1)==UI_STATUS_OK && state(tree).selected_id==((UINT64_C(2)<<32)|1),"first shared child has path-specific stable UI identity");
    check(ui_component_expand(tree,left_node,1)==UI_STATUS_OK && ui_component_query(tree,left_node,0,32,0,0)==UI_STATUS_OK,"query second shared parent without expanding arrays");tree_until=GetTickCount64()+5000;while(state(tree).cached_rows<4 && GetTickCount64()<tree_until){pump(&t);Sleep(1);}check(ui_component_select(tree,(UINT64_C(3)<<32)|1)==UI_STATUS_OK && state(tree).selected_id==((UINT64_C(3)<<32)|1),"same business Cell in second path has distinct UI identity");queued_contract(&t,first,tree);
    check(command(&t,first,"klayoutc.cell","{\"name\":\"TOP\"}",1) && command(&t,first,"klayoutc.select",select_json,1) && idle(&t,first),"prepare original object for deleted-target draft check");form=component(&t,first,"klayoutc.properties");check(field(form,"dx",UI_VALUE_NUMBER,"0.005",UI_VALUE_MODIFIED) && command(&t,first,"klayoutc.delete","{}",1),"deleting an object retains its pending draft identity");check(command(&t,first,"klayoutc.properties_submit","{}",0),"deleted original target refuses draft submit");draft.size=sizeof(draft);(void)ui_component_get_field(form,"dx",&draft);check(draft.text && !strcmp(draft.text,"0.005") && (draft.flags&UI_VALUE_MODIFIED),"failed draft keeps input and modified flag");check(command(&t,first,"klayoutc.undo","{}",1) && command(&t,first,"klayoutc.properties_submit","{}",1),"undo restores original identity and revalidates unchanged properties");check(command(&t,first,"klayoutc.undo","{}",1) && command(&t,first,"klayoutc.cell","{\"name\":\"LEFT\"}",1),"restore fixture geometry and current Cell after draft test");
    uint64_t pending=0;check(ui_workspace_invoke(t.workspace,first,"klayoutc.cell_rename","{}",&pending)==UI_STATUS_OK && pending,"asynchronous parameter command remains pending");ui_component_t *dialog=component(&t,first,"klayoutc.dialog.cell");ULONGLONG modal_until=GetTickCount64()+5000;while(dialog && !state(dialog).modal && GetTickCount64()<modal_until){pump(&t);Sleep(1);}check(dialog && state(dialog).modal,"parameter dialog uses instance modal");if(!dialog || !state(dialog).modal){fprintf(stderr,"MODAL_FAILURE: %s\n",snapshot(&t,first));(void)command(&t,first,"klayoutc.dialog_cancel","{}",1);goto cleanup;}check(command(&t,second,"klayoutc.grid","{\"visible\":1}",1),"other instance remains independently usable");check(type_dialog_name(&t,dialog) && command(&t,first,"klayoutc.dialog_submit","{}",1),"dialog resumes semantic rename and accepts input");check(has(&t,first,"\"cell\":\"RENAMED\""),"rename changed expected current Cell");
    check(command(&t,first,"klayoutc.cell_rename","{\"name\":\"TOP\"}",0),"duplicate Cell name rejected");
    for(int dpi=96;dpi<=192;dpi+=48){rect.width=620;rect.height=430;check(ui_workspace_set_rect(t.workspace,&rect,dpi)==UI_STATUS_OK && idle(&t,first),"simulated DPI and shrink path completes actual frame");}rect.width=1180;rect.height=790;(void)ui_workspace_set_rect(t.workspace,&rect,96);ShowWindow(root,SW_MINIMIZE);pump(&t);ShowWindow(root,SW_RESTORE);check(idle(&t,first),"minimize restore completes actual OpenGL frame");
    SetWindowPos(root,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_SHOWWINDOW);(void)SetForegroundWindow(root);for(int i=0;i<20;++i){pump(&t);Sleep(5);}HWND actual_canvas=child(info(&t,first).native_container,L"UiFrameworkSurface");RECT actual_rect={0};GetWindowRect(actual_canvas,&actual_rect);POINT actual_center={(actual_rect.left+actual_rect.right)/2,(actual_rect.top+actual_rect.bottom)/2};HDC desktop_dc=GetDC(NULL);COLORREF actual_color=GetPixel(desktop_dc,actual_center.x,actual_center.y);ReleaseDC(NULL,desktop_dc);fprintf(stderr,"CANVAS_SCREEN: visible %d enabled %d rect %ld,%ld-%ld,%ld center owner %p canvas %p currentGL %p rgb %06lX state %s\n",IsWindowVisible(actual_canvas),IsWindowEnabled(actual_canvas),actual_rect.left,actual_rect.top,actual_rect.right,actual_rect.bottom,WindowFromPoint(actual_center),actual_canvas,WindowFromDC(wglGetCurrentDC()),actual_color,snapshot(&t,first));check(actual_color!=0 && WindowFromPoint(actual_center)==actual_canvas,"actual visible OpenGL canvas presents nonblack geometry pixels");check(GetForegroundWindow()==root,"owned verification window actually becomes foreground");check(GetForegroundWindow()==root && capture(root,L"workflow-workspace.bmp"),"capture actual owned current workspace and OpenGL content");
    save_fixture(&t,first,"workflow-hierarchy.gds");check(ui_workspace_close(t.workspace,first,UI_APP_CLOSE_TAB)!=UI_STATUS_CANCELLED,"saved close waits for actual worker exit");ULONGLONG until=GetTickCount64()+15000;while(info(&t,first).host && GetTickCount64()<until){pump(&t);Sleep(1);}check(!info(&t,first).host && info(&t,second).host,"closing one instance keeps second alive");
    layer_dialog_contract(&t,second);paging_contract(&t,second);close_instance(&t,second);uint64_t reopened=0;check(ui_workspace_open(t.workspace,package,&reopened)==UI_STATUS_OK && idle(&t,reopened),"unload then reload matched package");check(command(&t,reopened,"klayoutc.add_box","{\"x1\":0,\"y1\":0,\"x2\":5,\"y2\":5}",1),"make reloaded document unsaved for close confirmation");close_failure_contract(&t,reopened);close_instance(&t,reopened);
cleanup:
    while(ui_workspace_count(t.workspace)){uint64_t id=ui_workspace_instance_at(t.workspace,0);close_instance(&t,id);if(info(&t,id).host)break;}
    check(ui_workspace_destroy(t.workspace)==UI_STATUS_OK,"all callbacks workers and modules permit workspace destruction");SetWindowLongPtrW(root,GWLP_USERDATA,0);if(argc==3 && !wcscmp(argv[2],L"--workspace-input"))workspace_profile(&t,root,package,&config,profile);DestroyWindow(root);free(package);fprintf(stderr,"REGRESSION_RESULT: %u checks %u failures\n",checks,failures);return failures?1:0;
}
